-- Arathi 38-39 Guide
-- Based on https://www.sageguide.net/38-39_arathi

LevelingGuide_Arathi = {
  steps = {
    { action="accept", quest=691, name="Worth Its Weight in Gold", npc="Apprentice Kryten", coords={x=46.2,y=47.7} },
    { action="info", quest=642, name="The Princess Trapped", item="Shards of Myzreal", coords={x=63.0,y=34.0}, note="Click Shards of Myzreal to accept the Quest." },
    { action="collect", quest=642, name="The Princess Trapped", item="Mote of Myzrael", coords={x=81.3,y=39.9}, note="Kill Drywhiskers for Mote of Myzrael. Follow the path and enter the cave." },
    { action="turnin", quest=642, name="The Princess Trapped", npc="Iridescent Shards", coords={x=84.3,y=30.9}, note="Click Iridescent Shards to turn-in the Quest." },
    { action="accept", quest=651, name="Stones of Binding", npc="Iridescent Shards", coords={x=84.3,y=30.9} },
    { action="collect", quest=651, name="Stones of Binding", item="Cresting Key", coords={x=66.7,y=29.7}, note="Click Stone of East Binding to pick up Cresting Key." },
    { action="collect", quest=691, name="Worth Its Weight in Gold", item={"Shadow Hunter Knife","Witherbark Medicine Pouch","Witherbark Tusk"}, coords={x=68.3,y=74.5}, note="Kill Witherbark Shadow Hunter for the knife, Witch Doctor for the pouch, Headhunter for the tusk. Enter the cave and take the right path." },
    { action="turnin", quest=659, name="Hints of a New Plague?", npc="Quae", coords={x=60.0,y=54.0} },
    { action="accept", quest=658, name="Hints of a New Plague?", npc="Quae", coords={x=60.0,y=54.0} },
    { action="collect", quest=658, name="Hints of a New Plague?", item="Sealed Folder", coords={x=60.2,y=59.1}, note="Kill Forsaken Courier if found patrolling the road to pick up Sealed Folder." },
    { action="turnin", quest=658, name="Hints of a New Plague?", npc="Quae", coords={x=60.0,y=54.0} },
    { action="accept", quest=657, name="Hints of a New Plague?", npc="Quae", coords={x=60.0,y=54.0} },
    { action="turnin", quest=657, name="Hints of a New Plague?", npc="Kinelory", coords={x=60.2,y=53.9} },
    { action="accept", quest=660, name="Hints of a New Plague?", npc="Kinelory", coords={x=60.2,y=53.9} },
    { action="info", name="Escort Kinelory", note="Escort Kinelory across the farm and back to Quae.", coords={x=60.0,y=54.0} },
    { action="turnin", quest=660, name="Hints of a New Plague?", npc="Quae", coords={x=60.0,y=54.0} },
    { action="accept", quest=661, name="Hints of a New Plague?", npc="Quae", coords={x=60.0,y=54.0} },
    { action="collect", quest=651, name="Stones of Binding", item="Thundering Key", coords={x=52.0,y=50.7}, note="Click Stone of Outer Binding to pick up Thundering Key." },
    { action="turnin", quest=691, name="Worth Its Weight in Gold", npc="Apprentice Kryten", coords={x=46.2,y=47.7} },
    { action="accept", quest=693, name="Wand over Fist", npc="Skuerto", coords={x=46.6,y=47.0} },
    { action="info", quest=693, name="Wand over Fist", coords={x=53.6,y=76.8}, note="Enter the cave and take the left path." },
    { action="collect", quest=693, name="Wand over Fist", item="Trelane's Wand of Invocation", coords={x=54.7,y=81.9}, note="Kill Kor'gresh Coldrage for Trelane's Wand of Invocation. Take left path." },
    { action="turnin", quest=693, name="Wand over Fist", npc="Skuerto", coords={x=46.6,y=47.0} },
    { action="accept", quest=681, name="Northfold Manor", npc="Captain Nials", coords={x=45.8,y=47.5} },
    { action="kill", quest=681, name="Northfold Manor", mob={"Syndicate Highwayman","Syndicate Mercenary"}, coords={x=30.9,y=29.8} },
    { action="collect", quest=651, name="Stones of Binding", item="Burning Key", coords={x=25.5,y=30.1}, note="Click Stone of West Binding to pick up Burning Key." },
    { action="turnin", quest=681, name="Northfold Manor", npc="Captain Nials", coords={x=45.8,y=47.5} },
    { action="turnin", quest=651, name="Stones of Binding", npc="Stone of Inner Binding", coords={x=36.2,y=57.4}, note="Click Stone of Inner Binding to turn-in Quest." },
    { action="info", name="Faldir's Cove", note="Run along south outer edge of Stromgarde Keep and through the cave.", coords={x=21.4,y=72.6} },
    { action="accept", quest=663, name="Land Ho!", npc="Lolo the Lookout", coords={x=31.8,y=82.7} },
    { action="turnin", quest=663, name="Land Ho!", npc="Shakes O'Breen", coords={x=32.2,y=81.4} },
    { action="accept", quest=662, name="Deep Sea Salvage", npc="First Mate Nilzlix", coords={x=32.8,y=81.5} },
    { action="accept", quest=664, name="Drowned Sorrows", npc="Captain Steelgut", coords={x=34.0,y=80.8} },
    { action="accept", quest=665, name="Sunken Treasure", npc="Professor Phizzlethorpe", coords={x=33.9,y=80.5} },
    { action="info", name="Escort", note="Escort Professor Phizzlethorpe. Two Level 40 water elementals will spawn, kill one at a time.", coords={x=35.8,y=79.6} },
    { action="turnin", quest=665, name="Sunken Treasure", npc="Doctor Draxlegauge", coords={x=33.8,y=80.5} },
    { action="accept", quest=666, name="Sunken Treasure", npc="Doctor Draxlegauge", coords={x=33.8,y=80.5} },
    { action="info", name="Equip", note="Equip Goggles of Gem Hunting.", coords={x=33.8,y=80.5} },
    { action="collect", quest=662, name="Deep Sea Salvage", item="Maiden's Folly Log", coords={x=23.4,y=85.1}, note="East ship, middle floor near junkpile." },
    { action="collect", quest=662, name="Deep Sea Salvage", item="Maiden's Folly Charts", coords={x=23.0,y=84.5}, note="East ship, middle floor near mast." },
    { action="collect", quest=662, name="Deep Sea Salvage", item="Spirit of Silverpine Charts", coords={x=20.5,y=85.6}, note="West ship, middle floor near cannon and crates (swim through leftmost window)." },
    { action="collect", quest=662, name="Deep Sea Salvage", item="Spirit of Silverpine Log", coords={x=20.6,y=85.1}, note="West ship in the basement, swim down through hole in the ship." },
    { action="kill", quest=664, name="Drowned Sorrows", mob={"Daggerspine Raider","Daggerspine Sorceress"}, coords={x=23.0,y=85.0} },
    { action="collect", quest=666, name="Sunken Treasure", item="Elven Gem", coords={x=24.5,y=86.4}, note="Loot Calcified Elven Gems to collect Elven Gems. They are on the seafloor." },
    { action="turnin", quest=662, name="Deep Sea Salvage", npc="First Mate Nilzlix", coords={x=32.8,y=81.5} },
    { action="turnin", quest=664, name="Drowned Sorrows", npc="Captain Steelgut", coords={x=34.0,y=80.8} },
    { action="turnin", quest=666, name="Sunken Treasure", npc="Professor Phizzlethorpe", coords={x=33.9,y=80.5} },
    { action="accept", quest=668, name="Sunken Treasure", npc="Professor Phizzlethorpe", coords={x=33.9,y=80.5} },
    { action="turnin", quest=668, name="Sunken Treasure", npc="Shakes O'Breen", coords={x=32.2,y=81.4} },
    { action="accept", quest=669, name="Sunken Treasure", npc="Shakes O'Breen", coords={x=32.2,y=81.4} },
    { action="info", name="Equip", note="Don't forget to put your helmet back on!", coords={x=32.2,y=81.4} },
    { action="info", name="Hearth to Southshore", note="Use Hearthstone to return to Southshore.", coords={x=32.2,y=81.4} },
    { action="turnin", quest=661, name="Hints of a New Plague?", npc="Phin Odelic", coords={x=50.4,y=59.0} },
    { action="info", name="Ironforge", note="Use Teleport: Ironforge or fly to Ironforge.", coords={x=49.3,y=52.3} },
    { action="turnin", quest=554, name="Stormpike's Deciphering", npc="Prospector Stormpike", coords={x=74.6,y=11.8} },
    { action="turnin", quest=1050, name="Mythology of the Titans", npc="Librarian Mae Paledust", coords={x=75.0,y=12.5}, note="Only if you did Scarlet Monastery." },
    { action="info", name="Set Hearthstone", note="Bind your Hearthstone to Ironforge at Innkeeper Firebrew.", coords={x=18.0,y=51.0} },
    { action="info", name="Bank", note="Deposit to Bank: Sample Elven Gem.", coords={x=35.5,y=60.6} },
    { action="info", name="Bank", note="Withdraw from Bank: Fizzle Brassbolts' Letter", coords={x=35.5,y=60.6} },
    { action="info", name="Thelsamar", note="Fly to Thelsamar.", coords={x=55.5,y=47.8} },
    { action="accept", quest=2500, name="Badlands Reagent Run", npc="Ghak Healtouch", coords={x=37.1,y=49.3} },
    { action="turnin", quest=707, name="Ironband Wants You!", npc="Prospector Ironband", coords={x=65.9,y=65.6} },
    { action="accept", quest=738, name="Find Agmond", npc="Prospector Ironband", coords={x=65.9,y=65.6} },
    { nextGuide = "Badlands 39-40.lua" },
  }
}