LevelingGuide_Azshara = {
  steps = {
    -- Talrendis Point quests
    { action="accept", quest=5535, name="Spiritual Unrest", npc="Loh'atu", coords={x=11.4,y=78.2} },
    { action="accept", quest=5536, name="A Land Filled with Hatred", npc="Loh'atu", coords={x=11.4,y=78.2} },
    { action="kill", quest=5535, name="Spiritual Unrest", mob={"Highborne Apparition","Highborne Lichling"}, coords={x=16.7,y=70.5} },
    { action="kill", quest=5536, name="A Land Filled with Hatred", mob={"Haldarr Satyr","Haldarr Trickster","Haldarr Felsworn"}, coords={x=20.0,y=62.0} },
    { action="turnin", quest=5535, name="Spiritual Unrest", npc="Loh'atu", coords={x=11.4,y=78.2} },
    { action="turnin", quest=5536, name="A Land Filled with Hatred", npc="Loh'atu", coords={x=11.4,y=78.2} },
    { action="accept", quest=3601, name="Kim'jael Indeed!", npc="Kim'jael", coords={x=53.5,y=21.8}, note="He is up on the hill." },
    { action="collect", quest=3601, name="Kim'jael Indeed!", item={"Kim'Jael's Compass","Kim'jael's Scope","Kim'jael's Stuffed Chicken","Kim'jael's Wizzlegoober"}, coords={x=58.5,y=25.0}, note="Click Kim'jael's Equipment chests." },
    { action="turnin", quest=3601, name="Kim'jael Indeed!", npc="Kim'jael", coords={x=53.5,y=21.8} },
    { action="accept", quest=5534, name="Kim'jael's \"Missing\" Equipment", npc="Kim'jael", coords={x=53.5,y=21.8} },
    { action="collect", quest=3449, name="Arcane Runes", item="Rubbing: Rune of Jin'yael", coords={x=39.5,y=50.2}, note="Click Rune of Jin'yael for Rubbing: Rune of Jin'yael." },
    { action="collect", quest=3449, name="Arcane Runes", item="Rubbing: Rune of Beth'Amara", coords={x=36.9,y=53.1}, note="Click Rune of Beth'Amara for Rubbing: Rune of Beth'Amara." },
    { action="collect", quest=3449, name="Arcane Runes", item="Rubbing: Rune of Markri", coords={x=39.4,y=55.4}, note="Click Rune of Markri for Rubbing: Rune of Markri." },
    { action="collect", quest=3449, name="Arcane Runes", item="Rubbing: Rune of Sael'hai", coords={x=42.3,y=64.1}, note="Click the Rune of Sael'hai for Rubbing: Rune of Sael'hai." },
    { action="collect", quest=5534, name="Kim'jael's \"Missing\" Equipment", item="Some Rune", coords={x=38.1,y=52.8}, note="Kill Spitelash Naga to pick up Some Rune." },
    { action="turnin", quest=5534, name="Kim'jael's \"Missing\" Equipment", npc="Kim'jael", coords={x=53.5,y=21.8} },
    { action="info", name="Island", note="Go to the small island.", coords={x=77.8,y=91.3} },
    { action="info", name="Use Flare Gun", coords={x=77.8,y=91.3}, note="Use the Standard Issue Flare Gun in your inventory to summon Pilot Xiggs Fuselighter." },
    { action="turnin", quest=3449, name="Arcane Runes", npc="Pilot Xiggs Fuselighter", coords={x=77.8,y=91.5} },
    { action="accept", quest=3461, name="Return to Tymor", npc="Pilot Xiggs Fuselighter", coords={x=77.8,y=91.5} },
    { action="info", name="Destroy Flare Gun", note="Destroy the Standard Issue Flare Gun from your inventory.", coords={x=77.8,y=91.5} },
    { action="info", name="Astranaar", note="Use Hearthstone to return to Astranaar.", coords={x=77.8,y=91.5} },
    { action="info", name="Theramore", note="Fly to Theramore.", coords={x=34.4,y=48.0} },
    { action="info", name="Boat to Menethil", note="Take the Boat to Menethil.", coords={x=71.5,y=56.3} },
    { action="info", name="Aerie Peak", note="Fly to Aerie Peak in The Hinterlands.", coords={x=9.5,y=59.7} },
    { action="info", name="Hearthstone", note="Bind your Hearthstone to Wildhammer Keep at Innkeeper Thulfram. He is upstairs.", coords={x=13.6,y=41.7} },
    { action="turnin", quest=1452, name="Rhapsody's Kalimdor Kocktail", npc="Rhapsody Shindigger", coords={x=26.9,y=48.5} },
    { action="accept", quest=1469, name="Rhapsody's Tale", npc="Rhapsody Shindigger", coords={x=26.9,y=48.5}, note="Wait for RPG, then accept this Quest." },
    { action="collect", quest=2641, name="Sprinkle's Secret Ingredient", item="Violet Tragan", coords={x=40.7,y=59.0}, note="Click Violet Tragan underwater to pick it up." },
    { action="info", name="Southshore", note="Fly to Chillwind Camp in Western Plaguelands.", coords={x=11.0,y=46.0} },
    --{ action="info", name="Alterac", note="Go to Alterac Mountains.", coords={x=31.7,y=27.0} },
    --{ action="turnin", quest=40164, name="The Tower of Lapidis II", npc="Archmage Ansirem Runeweaver", coords={x=18.8,y=78.5}, note="TurtleWoW specific." },
    { nextGuide = "Western Plaguelands 53-54.lua" }
  }
}