LevelingGuide_Badlands = {
  steps = {
    { action="info", name="Badlands", note="Go to the Badlands.", coords={x=47.2,y=81.8} },
    { action="accept", quest=718, name="Mirages", npc="Sigrun Ironhew", coords={x=53.8,y=43.3} },
    { action="accept", quest=719, name="A Dwarf and His Tools", npc="Prospector Ryedol", coords={x=53.4,y=43.4} },
    { action="accept", quest=40229, name="Angor Fortress", npc="Senator Broadbelt", coords={x=53.6,y=43.1}, note="TurtleWoW specific." },
    { action="accept", quest=40228, name="Captain Barlgruf", npc="Senator Broadbelt", coords={x=53.6,y=43.1}, note="TurtleWoW specific." },
    { action="accept", quest=720, name="A Sign of Hope", npc=="Crumpled Map", coords={x=53.0,y=33.9}, note="Click the Crumpled Map below the table to accept Quest." },
    { action="collect", quest=719, name="A Dwarf and His Tools", item="Ryedol's Lucky Pick", coords={x=53.7,y=30.6}, note="Kill Shadowforge dwarves to pick up Ryedol's Lucky Pick." },
    { action="collect", quest=718, name="Mirages", item="Excavation Supply Crate", coords={x=66.9,y=23.4}, note="Loot Excavation Supply Crate near the cauldron." },
    { action="turnin", quest=718, name="Mirages", npc="Sigrun Ironhew", coords={x=53.7,y=43.3}, note="Turn in Mirages to Sigrun Ironhew." },
    { action="accept", quest=733, name="Scrounging", npc="Sigrun Ironhew", coords={x=53.7,y=43.3} },
    { action="turnin", quest=719, name="A Dwarf and His Tools", npc="Prospector Ryedol", coords={x=53.7,y=43.6} },
    { action="turnin", quest=720, name="A Sign of Hope", npc="Prospector Ryedol", coords={x=53.7,y=43.6} },
    { action="accept", quest=721, name="A Sign of Hope", npc="Prospector Ryedol", coords={x=53.7,y=43.6} },
    { action="turnin", quest=721, name="A Sign of Hope", npc="Hammertoe Grez", coords={x=48.8,y=29.8}, note="He is located in the cave to Uldaman." },
    { action="accept", quest=722, name="Amulet of Secrets", npc="Hammertoe Grez", coords={x=48.8,y=29.8} },
    { action="info", name="Shattered Necklace", note="Kill Shadowforge dwarves for Shattered Necklace. This item starts a Quest.", coords={x=48.3,y=13.2} },
    { action="kill", quest=40228, name="Captain Barlgruf", mob="Captain Barlgruf", coords={x=41.4,y=29.8}, note="He is on the upper floor. TurtleWoW specific." },
    { action="collect", quest=40229, name="Angor Fortress", item="Shadowforge Shackle", coords={x=44.6,y=31.5}, note="Kill Shadowforge dwarves to collect Shadowforge Shackles. TurtleWoW specific." },
    { action="turnin", quest=40229, name="Angor Fortress", npc="Senator Broadbelt", coords={x=53.6,y=43.1}, note="TurtleWoW specific." },
    { action="turnin", quest=40228, name="Captain Barlgruf", npc="Senator Broadbelt", coords={x=53.6,y=43.1}, note="TurtleWoW specific." },
    { action="accept", quest=710, name="Study of the Elements: Rock", npc="Lotwil Veriatus", coords={x=25.9,y=44.8} },
    { action="collect", quest=710, name="Study of the Elements: Rock", item="Small Stone Shard", coords={x=20,y=45}, note="Kill Lesser Rock Elementals to pick up Small Stone Shards." },
    { action="collect", quest=2500, name="Badlands Reagent Run", item="Rock Elemental Shard", coords={x=20,y=45}, note="Kill (Lesser) Rock Elementals to pick up Rock Elemental Shards." },
    { action="turnin", quest=710, name="Study of the Elements: Rock", npc="Lotwil Veriatus", coords={x=25.9,y=44.8} },
    { action="accept", quest=711, name="Study of the Elements: Rock", npc="Lotwil Veriatus", coords={x=25.9,y=44.8} },
    { action="turnin", quest=1106, name="Martek the Exiled", npc="Martek the Exiled", coords={x=42.2,y=52.9} },
    { action="accept", quest=1108, name="Indurium", npc="Martek the Exiled", coords={x=42.2,y=52.9} },
    { action="accept", quest=703, name="Barbecued Buzzard Wings", npc="Rigglefuzz", coords={x=42.4,y=52.9} },
    { action="turnin", quest=738, name="Find Agmond", npc="Battered Dwarven Skeleton", coords={x=50.9,y=62.4}, note="Click Battered Dwarven Skeleton to turn in Find Agmond." },
    { action="accept", quest=739, name="Murdaloc", npc="Battered Dwarven Skeleton", coords={x=50.9,y=62.4} },
    { action="kill", quest=739, name="Murdaloc", mob={"Stonevault Bonesnapper","Murdaloc"}, coords={x=49.6,y=66.3} },
    { action="collect", quest=1108, name="Indurium", item="Indurium Flake", coords={x=51,y=62}, note="Kill Stonevaults mobs to pick up Indurium Flakes." },
    { action="accept", quest=709, name="Solution to Doom", npc="Theldurin the Lost", coords={x=51.4,y=76.8} },
    { action="collect", quest=711, name="Study of the Elements: Rock", item="Large Stone Slab", coords={x=45.3,y=79.7}, note="Kill Rock Elementals to pick up Large Stone Slabs." },
    { action="collect", quest=2500, name="Badlands Reagent Run", item={"Buzzard Gizzard","Crag Coyote Fang"}, coords={x=33.8,y=66.8}, note="Kill Buzzards for Buzzard Gizzards. Kill Feral Crag Coyotes for Crag Coyote Fangs." },
    { action="collect", quest=703, name="Barbecued Buzzard Wings", item="Buzzard Wing", coords={x=18.1,y=59.2}, note="Kill Buzzards to pick up Buzzard Wings." },
    { action="turnin", quest=1108, name="Indurium", npc="Martek the Exiled", coords={x=42.2,y=52.9} },
    { action="accept", quest=1137, name="News for Fizzle", npc="Martek the Exiled", coords={x=42.2,y=52.9}, note="Wait for RPG to accept Quest." },
    { action="turnin", quest=703, name="Barbecued Buzzard Wings", npc="Rigglefuzz", coords={x=42.4,y=52.9} },
    { action="accept", quest=2418, name="Power Stones", npc="Rigglefuzz", coords={x=42.4,y=52.9} },
    { action="turnin", quest=711, name="Study of the Elements: Rock", npc="Lotwil Veriatus", coords={x=25.9,y=44.8} },
    { action="accept", quest=712, name="Study of the Elements: Rock", npc="Lotwil Veriatus", coords={x=25.9,y=44.8} },
    { action="collect", quest=733, name="Scrounging", item="Scrap Metal", coords={x=12.8,y=73.7}, note="Kill Dustbelcher ogres to pick up Scrap Metal." },
    { action="collect", quest=712, name="Study of the Elements: Rock", item="Bracers of Rock Binding", coords={x=13.3,y=84.0}, note="Kill Greater Rock Elementals to collect Bracers of Rock Binding." },
    { action="turnin", quest=712, name="Study of the Elements: Rock", npc="Lotwil Veriatus", coords={x=25.9,y=44.8} },
    { action="info", name="Grind", note="Grind nearby until you reach Level 40.", coords={x=25.9,y=44.8} },
    { action="info", name="Ironforge", note="Use Hearthstone to return to Ironforge.", coords={x=25.9,y=44.8} },
    { action="info", name="Auction House", note="Buy 5 Silver Bars from the Auction House.", coords={x=24.2,y=74.4} },
    { action="info", quest=2198, name="The Shattered Necklace", target="Shattered Necklace", coords={x=33.1,y=64.9}, note="Use Shattered Necklace in your inventory to accept Quest." },
    { action="turnin", quest=2198, name="The Shattered Necklace", npc="Talvash del Kissel", coords={x=36.4,y=3.6} },
    { action="accept", quest=2199, name="Lore for a Price", npc="Talvash del Kissel", coords={x=36.4,y=3.6} },
    { action="turnin", quest=2199, name="Lore for a Price", npc="Talvash del Kissel", coords={x=36.4,y=3.6}, note="Requires 5 Silver Bars to be turned-in." },
    { action="accept", quest=2200, name="Back to Uldaman", npc="Talvash del Kissel", coords={x=36.4,y=3.6} },
    { action="accept", quest=1360, name="Reclaimed Treasures", npc="Krom Stoutarm", coords={x=74.2,y=9.4} },
    { action="accept", quest=2398, name="The Lost Dwarves", npc="Prospector Stormpike", coords={x=74.5,y=11.7} },
    { action="accept", quest=41754, name="The Redbrand Lie", npc="Redbrand Tablet", coords={x=70.4,y=17.6}, note="TurtleWoW specific." },
    { action="turnin", quest=41754, name="The Redbrand Lie", npc="Torwyn Redbrand", coords={x=19.6,y=24.4}, note="TurtleWoW specific." },
    { action="info", name="Thelsamar", note="Fly to Thelsamar.", coords={x=55.5,y=47.8} },
    { action="turnin", quest=2500, name="Badlands Reagent Run", npc="Ghak Healtouch", coords={x=37.1,y=49.3} },
    { action="accept", quest=17, name="Uldaman Reagent Run", npc="Ghak Healtouch", coords={x=37.1,y=49.3} },
    { action="turnin", quest=739, name="Murdaloc", npc="Prospector Ironband", coords={x=65.9,y=65.6} },
    { action="accept", quest=704, name="Agmond's Fate", npc="Prospector Ironband", coords={x=65.9,y=65.6} },
    { action="info", name="Badlands", note="Go to the Badlands.", coords={x=47.2,y=81.8} },
    { action="collect", quest=2418, name="Power Stones", item={"Dentrium Power Stone","An'Alleum Power Stone"}, coords={x=44.7,y=13.1}, note="Kill Shadowforge dwarves for Dentrium Power Stones and An'Alleum Power Stones." },
    { action="info", name="Uldaman", note="Go into the cave.", coords={x=44.6,y=12.5} },
    { action="collect", quest=704, name="Agmond's Fate", item="Carved Stone Urn", coords={x=70.5,y=27.0}, note="Click Carved Stone Urn to collect Carved Stone Urn." },
    { action="collect", quest=17, name="Uldaman Reagent Run", item="Magenta Fungus Cap", coords={x=61.1,y=29.8}, note="Click Magenta Cap Clusters to collect Magenta Fungus Caps." },
    
    --[[
    { action="kill", quest=722, name="Amulet of Secrets", mob="Magregan Deepshadow", coords={x=43,y=13.5}, note="Kill Magregan Deepshadow for Hammertoe's Amulet." },
    { action="collect", quest=709, name="Solution to Doom", item="Tablet of Ryun'eh", coords={x=43,y=13.5}, note="Loot Ancient Chest for Tablet of Ryun'eh." },
    { action="collect", quest=1360, name="Reclaimed Treasures", item="Krom Stoutarm's Treasure", coords={x=43,y=13.5}, note="Loot Krom Stoutarm's Treasure." },
    { action="turnin", quest=722, name="Amulet of Secrets", npc="Hammertoe Grez", coords={x=43,y=13.5}, note="Turn in Amulet of Secrets to Hammertoe Grez." },
    { action="accept", quest=723, name="Prospect of Faith", npc="Hammertoe Grez", coords={x=43,y=13.5}, note="Accept Prospect of Faith from Hammertoe Grez." },
    
    -- Enter Uldaman proper
    { action="info", name="Enter Uldaman Dungeon", note="Enter Uldaman dungeon proper (GROUP 5+ recommended for full run).", coords={x=43,y=13.5} },
    { action="turnin", quest=2398, name="The Lost Dwarves", npc="Baelog", coords={x=43,y=13.5}, note="Find Baelog in the dirt room and turn in The Lost Dwarves." },
    { action="accept", quest=2240, name="The Hidden Chamber", npc="Baelog", coords={x=43,y=13.5}, note="Accept The Hidden Chamber from Baelog." },
    { action="turnin", quest=2200, name="Back to Uldaman", npc="Remains of a Paladin", coords={x=43,y=13.5}, note="Find Remains of a Paladin in the green halls and turn in Back to Uldaman." },
    { action="accept", quest=2201, name="Find the Gems", npc="Remains of a Paladin", coords={x=43,y=13.5}, note="Accept Find the Gems from Remains of a Paladin." },
    
    -- Optional full Uldaman run
    { action="info", name="Optional Full Run", note="GROUP 5+: You can continue full Uldaman and finish The Hidden Chamber and Find the Gems quests. Otherwise abandon them.", coords={x=43,y=13.5} },
    --]]
    -- Return to Ironforge
    --{ action="info", name="Ironforge", note="Use Hearthstone to return to Ironforge.", coords={x=32,y=36} },
    --{ action="turnin", quest=1360, name="Reclaimed Treasures", npc="Krom Stoutarm", coords={x=74.2,y=9.4} },
    --{ action="info", name="Thelsamar", note="Fly to Thelsamar.", coords={x=55.5,y=47.8} },
    --{ action="turnin", quest=17, name="Uldaman Reagent Run", npc="Ghak Healtouch", coords={x=37.0,y=49.0}, note="Turn in Uldaman Reagent Run to Ghak Healtouch. Save Restorative Potion for Level 60 raiding." },
    { action="turnin", quest=704, name="Agmond's Fate", npc="Prospector Ironband", coords={x=65.9,y=65.6} },
    { action="info", name="Badlands", note="Go to the Badlands.", coords={x=47.2,y=81.8} },
    { action="turnin", quest=733, name="Scrounging", npc="Sigrun Ironhew", coords={x=53.7,y=43.3} },
    --{ action="turnin", quest=723, name="Prospect of Faith", npc="Prospector Ryedol", coords={x=53.7,y=43.6} },
    --{ action="accept", quest=724, name="Prospect of Faith", npc="Prospector Ryedol", coords={x=53.7,y=43.6} },
    { action="turnin", quest=2418, name="Power Stones", npc="Rigglefuzz", coords={x=42.4,y=52.9} },
    { action="accept", quest=732, name="Tremors of the Earth", npc="Garek", coords={x=61.8,y=54.2}},
    --{ action="turnin", quest=709, name="Solution to Doom", npc="Theldurin the Lost", coords={x=51.4,y=76.9} },
    { action="collect", quest=732, name="Tremors of the Earth", item="Sign of the Earth", coords={x=35.3,y=72.5}, note="Kill Boss Tho'grun to pick up Sign of the Earth." },
    --{ action="accept", quest=40648, name="Roses are Red, Dragons are Blue...", npc="Asza", coords={x=57.3,y=72.8}, note="TurtleWoW specific." },
    { action="turnin", quest=732, name="Tremors of the Earth", npc="Garek", coords={x=61.8,y=54.2} },
    --{ action="collect", quest=40648, name="Roses are Red, Dragons are Blue...", item="Jewel of Draconic Guile", coords={x=74.9,y=46.7}, note="Kill Drathos Runebreaker to pick up Jewel of Draconic Guile. TurtleWoW specific." },
    --{ action="turnin", quest=40648, name="Roses are Red, Dragons are Blue...", npc="Asza", coords={x=57.3,y=72.8}, note="TurtleWoW specific." },
    --{ action="info", name="Ironforge", note="Use Teleport: Ironforge or run north to Thelsamar and fly to Ironforge.", coords={x=32,y=36} },

    --{ action="turnin", quest=724, name="Prospect of Faith", npc="Historian Karnik", coords={x=77.2,y=11.8}, note="Turn in Prospect of Faith to Historian Karnik at Hall of Explorers." },
    --{ action="accept", quest=725, name="Passing Word of a Threat", npc="Historian Karnik", coords={x=77.2,y=11.8}, note="Accept Passing Word of a Threat from Historian Karnik." },
    --{ action="turnin", quest=725, name="Passing Word of a Threat", npc="Advisor Belgrum", coords={x=77.2,y=9.7}, note="Turn in Passing Word of a Threat to Advisor Belgrum." },
    --{ action="accept", quest=726, name="Passing Word of a Threat", npc="Advisor Belgrum", coords={x=77.2,y=9.7}, note="Accept the follow-up Passing Word of a Threat quest." },
    --{ action="turnin", quest=726, name="Passing Word of a Threat", npc="Historian Karnik", coords={x=77.2,y=11.8}, note="Turn in Passing Word of a Threat to Historian Karnik." },
    { action="info", name="Stormwind", note="Use Teleport: Stormwind or run north to Thelsamar and fly to Stormwind.", coords={x=74.6,y=51.0} },
    { action="accept", quest=1448, name="In Search of The Temple", npc="Brohann Caskbelly", coords={x=69.4,y=40.4} },
    { action="info", name="Booty Bay", note="Fly to Booty Bay.", coords={x=71.0,y=72.5} },
    { nextGuide = "Stranglethorn 40-42.lua" }
  }
}