LevelingGuide_Felwood = {
  steps = {
    { action="accept", quest=5155, name="Forces of Jaedenar", npc="Greta Mosshoof", coords={x=51.2,y=82.1} },
    { action="accept", quest=4421, name="The Corruption of the Jadefire", npc="Eridan Bluewind", coords={x=51.3,y=81.5} },
    { action="accept", quest=8460, name="Timbermaw Ally", npc="Grazle", coords={x=51.0,y=85.0} },
    { action="kill", quest=8460, name="Timbermaw Ally", mob={"Deadwood Warrior","Deadwood Pathfinder","Deadwood Gardener"}, coords={x=48.8,y=91.0} },
    { action="turnin", quest=8460, name="Timbermaw Ally", npc="Grazle", coords={x=51.0,y=85.0} },
    { action="info", name="Grind", note="Kill Deadwood Furbolgs until you become Unfriendly with Timbermaw Hold.", coords={x=48.8,y=91.0} },
    { action="collect", quest=4512, name="A Little Slime Goes a Long Way", item="Cursed Ooze", coords={x=42.0,y=68.1}, note="Use Package of Empty Ooze Containers in your inventory. Kill Cursed Oozes and use Empty Cursed Ooze Jar on their corpses." },
    { action="kill", quest=4421, name="The Corruption of the Jadefire", mob={"Xavathras","Jadefire Felsworn","Jadefire Shadowstalker","Jadefire Rogue"}, coords={x=32.0,y=67.0} },
    { action="collect", quest=4512, name="A Little Slime Goes a Long Way", item="Tainted Ooze", coords={x=40.7,y=59.6}, note="Kill Tainted Oozes and use Empty Cursed Ooze Jar on their corpses." },
    { action="kill", quest=5155, name="Forces of Jaedenar", mob={"Jaedenar Hound","Jaedenar Guardian","Jaedenar Adept","Jaedenar Cultist"}, coords={x=36.7,y=61.4} },
    { action="turnin", quest=5155, name="Forces of Jaedenar", npc="Greta Mosshoof", coords={x=51.2,y=82.1} },
    { action="accept", quest=5157, name="Collection of the Corrupt Water", npc="Greta Mosshoof", coords={x=51.2,y=82.1} },
    { action="turnin", quest=4421, name="The Corruption of the Jadefire", npc="Eridan Bluewind", coords={x=51.3,y=81.5} },
    { action="collect", quest=5157, name="Collection of the Corrupt Water", item="Corrupt Moonwell Water", coords={x=35.2,y=59.8}, note="Use Empty Canteen in your inventory." },
    { action="turnin", quest=5157, name="Collection of the Corrupt Water", npc="Greta Mosshoof", coords={x=51.2,y=82.1} },
    { action="accept", quest=5158, name="Seeking Spiritual Aid", npc="Greta Mosshoof", coords={x=51.2,y=82.1} },
    { action="info", name="Ashenvale", note="Go to Ashenvale.", coords={x=54.9,y=93.0} },
    { action="info", name="Azshara", note="Go to Azshara.", coords={x=95.3,y=48.4} },
    { action="info", name="Get Flight Path", note="Get the Talrendis Point Flight Path.", coords={x=11.9,y=77.6} },
    { action="info", name="Darnassus", note="Use Teleport: Darnassus or fly to Darnassus.", coords={x=11.9,y=77.6} },
    { action="accept", quest=4493, name="March of the Silithid", npc="Gracina Spiritmight", coords={x=41.8,y=85.6}, note="She is upstairs." },
    { action="accept", quest=5091, name="A Call to Arms: The Plaguelands!", npc="Herald Moonstalker", coords={x=38.3,y=20.5}, note="She is patrolling around here." },
    { action="turnin", quest=3790, name="Assisting Arch Druid Staghelm", npc="Arch Druid Fandral Staghelm", coords={x=35.0,y=9.0}, note="Atop the tower." },
    { action="accept", quest=3764, name="Un'Goro Soil", npc="Arch Druid Fandral Staghelm", coords={x=35.0,y=9.0} },
    { action="info", name="Astranaar", note="Use Hearthstone to return to Astranaar.", coords={x=35.0,y=9.0} },
    { action="info", name="Azshara", note="Fly to Talrendis Point in Azshara.", coords={x=34.4,y=48.0} },
    { nextGuide = "Azshara 53.lua" }
  }
}