LevelingGuide_Gilneas = { 
  steps = {
    { action="info", name="Silverpine Forest", note="Go to Silverpine Forest.", coords={x=13.7,y=46.1} },
    { action="info", name="Gilneas", note="Go to Gilneas.", coords={x=46.5,y=84.4} },
    { action="accept", quest=40944, name="Onward to Ravenshire", npc="Councilor Ravencrest", coords={x=44.2,y=22.0}, note="TurtleWoW specific." },
    { action="accept", quest=40939, name="Supplementing Rations", npc="Camp Chef Velden", coords={x=43.8,y=22.1}, note="TurtleWoW specific." },
    { action="accept", quest=40937, name="Nighthowl Nuisance", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="accept", quest=40936, name="Vagrant Supplies", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="accept", quest=40932, name="Wagon Woes", npc="Donald Rosewick", coords={x=44.3,y=35.6}, note="TurtleWoW specific." },
    { action="collect", quest=40936, name="Wagon Woes", item="Spare Wagon Wheel", coords={x=43.2,y=26.6}, note="Click Spare Wagon Wheel to pick up Spare Wagon Wheel. TurtleWoW specific." },
    { action="collect", quest=40937, name="Nighthowl Nuisance", item="Nighthowl Shackle", coords={x=44.3,y=27.2}, note="Kill Nighthowl Worgens to pick up Nighthowl Shackles. TurtleWoW specific." },
    { action="collect", quest=40936, name="Vagrant Supplies", item="Vagrant Supplies", coords={x=39.6,y=36.3}, note="Click Medical Crate to pick up Vagrant Supplies. TurtleWoW specific." },
    { action="collect", quest=40939, name="Supplementing Rations", item="Duskpelt Meat", coords={x=42.1,y=33.9}, note="Kill Duskpelt wolves to pick up Duskpelt Meat. TurtleWoW specific." },
    { action="turnin", quest=40937, name="Nighthowl Nuisance", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="accept", quest=40938, name="Nighthowl Neutralizing", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40936, name="Vagrant Supplies", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40939, name="Supplementing Rations", npc="Camp Chef Velden", coords={x=43.8,y=22.1}, note="TurtleWoW specific." },
    { action="kill", quest=40938, name="Nighthowl Neutralizing", mob="Nighthowl Alpha", coords={x=39.1,y=15.9}, note="TurtleWoW specific." },
    { action="turnin", quest=40938, name="Nighthowl Neutralizing", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40932, name="Wagon Woes", npc="Donald Rosewick", coords={x=44.3,y=35.6}, note="TurtleWoW specific." },
    { action="accept", quest=40933, name="Rosewick Worries", npc="Donald Rosewick", coords={x=44.3,y=35.6}, note="TurtleWoW specific." },
    { action="accept", quest=40907, name="The Haunting of Aliattan Anderson", npc="Aliattan Anderson", coords={x=50.3,y=47.9}, note="TurtleWoW specific." },
    { action="accept", quest=41034, name="A Vile Mantle", npc="Bearbane", coords={x=46.6,y=46.8}, note="TurtleWoW specific." },
    { action="accept", quest=41035, name="The Hound and the Hunter", npc="Levandra", coords={x=50.3,y=47.9}, note="TurtleWoW specific." },
    { action="accept", quest=41037, name="Rods for the Pellars", npc="Mustang", coords={x=45.7,y=43.7}, note="TurtleWoW specific." },
    { action="accept", quest=41036, name="Deathly Fetters", npc="Lurn Five-Pelts", coords={x=42.6,y=43.4}, note="TurtleWoW specific." },
    { action="collect", quest=40907, name="The Haunting of Aliattan Anderson", item="Aliattan Anderson's Journal", coords={x=39.3,y=55.5}, note="Click Aliattan Anderson's Journal to pick up Aliattan Anderson's Journal. TurtleWoW specific." },
    { action="collect", quest=41036, name="Deathly Fetters", item="Haunted Memento", coords={x=36.6,y=47.4}, note="Kill Undeads and click Memento of Greyshire on the ground to pick up Haunted Mementos. TurtleWoW specific." },
    { action="collect", quest=41037, name="Rods for the Pellars", item="Foulhide Talisman", coords={x=32.7,y=35.4}, note="Kill Foulhide Gnolls to pick up Foulhide Talismans. TurtleWoW specific." },
    { action="kill", quest=41035, name="The Hound and the Hunter", mob="Matthew Beckett", coords={x=50.3,y=47.9}, note="TurtleWoW specific." },
    { action="collect", quest=41034, name="A Vile Mantle", item={"Vilewing Pelt","Duskpelt Fur"}, coords={x=38.3,y=57.1}, note="TurtleWoW specific." },
    --{ action="accept", quest=40975, name="The Judge and the Phantom", npc="Angered Phantom", coords={x=52.5,y=28.5}, note="TurtleWoW specific." },
  }
}