LevelingGuide_Gilneas = { 
  steps = {
    { action="info", name="Silverpine Forest", note="Go to Silverpine Forest.", coords={x=13.7,y=46.1} },
    { action="info", name="Gilneas", note="Go to Gilneas.", coords={x=46.5,y=84.4} },
    { action="accept", quest=40944, name="Onward to Ravenshire", npc="Councilor Ravencrest", coords={x=44.2,y=22.0}, note="TurtleWoW specific." },
    { action="accept", quest=40939, name="Supplementing Rations", npc="Camp Chef Velden", coords={x=43.8,y=22.1}, note="TurtleWoW specific." },
    { action="accept", quest=40937, name="Nighthowl Nuisance", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="accept", quest=40936, name="Vagrant Supplies", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="accept", quest=40932, name="Wagon Woes", npc="Donald Rosewick", coords={x=44.3,y=35.6}, note="TurtleWoW specific." },
    { action="collect", quest=40936, name="Wagon Woes", item="Spare Wagon Wheel", coords={x=43.2,y=26.6}, note="Click Spare Wagon Wheel to pick up Spare Wagon Wheel. TurtleWoW specific." },
    { action="collect", quest=40937, name="Nighthowl Nuisance", item="Nighthowl Shackle", coords={x=44.3,y=27.2}, note="Kill Nighthowl Worgens to pick up Nighthowl Shackles. TurtleWoW specific." },
    { action="collect", quest=40936, name="Vagrant Supplies", item="Vagrant Supplies", coords={x=39.6,y=36.3}, note="Click Medical Crate to pick up Vagrant Supplies. TurtleWoW specific." },
    { action="collect", quest=40939, name="Supplementing Rations", item="Duskpelt Meat", coords={x=42.1,y=33.9}, note="Kill Duskpelt wolves to pick up Duskpelt Meat. TurtleWoW specific." },
    { action="turnin", quest=40937, name="Nighthowl Nuisance", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="accept", quest=40938, name="Nighthowl Neutralizing", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40936, name="Vagrant Supplies", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40939, name="Supplementing Rations", npc="Camp Chef Velden", coords={x=43.8,y=22.1}, note="TurtleWoW specific." },
    { action="kill", quest=40938, name="Nighthowl Neutralizing", mob="Nighthowl Alpha", coords={x=39.1,y=15.9}, note="TurtleWoW specific." },
    { action="turnin", quest=40938, name="Nighthowl Neutralizing", npc="Camp Leader Gethenor", coords={x=44.0,y=22.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40932, name="Wagon Woes", npc="Donald Rosewick", coords={x=44.3,y=35.6}, note="TurtleWoW specific." },
    { action="accept", quest=40933, name="Rosewick Worries", npc="Donald Rosewick", coords={x=44.3,y=35.6}, note="TurtleWoW specific." },
    { action="accept", quest=40907, name="The Haunting of Aliattan Anderson", npc="Aliattan Anderson", coords={x=50.3,y=47.9}, note="TurtleWoW specific." },
    { action="accept", quest=41034, name="A Vile Mantle", npc="Bearbane", coords={x=46.6,y=46.8}, note="TurtleWoW specific." },
    { action="accept", quest=41035, name="The Hound and the Hunter", npc="Levandra", coords={x=45.7,y=46.0}, note="TurtleWoW specific." },
    { action="accept", quest=41037, name="Rods for the Pellars", npc="Mustang", coords={x=45.7,y=43.7}, note="TurtleWoW specific." },
    { action="accept", quest=41036, name="Deathly Fetters", npc="Lurn Five-Pelts", coords={x=42.6,y=43.4}, note="TurtleWoW specific." },
    { action="collect", quest=40907, name="The Haunting of Aliattan Anderson", item="Aliattan Anderson's Journal", coords={x=39.3,y=55.5}, note="Click Aliattan Anderson's Journal to pick up Aliattan Anderson's Journal. TurtleWoW specific." },
    { action="collect", quest=41036, name="Deathly Fetters", item="Haunted Memento", coords={x=36.6,y=47.4}, note="Kill Undeads and click Memento of Greyshire on the ground to pick up Haunted Mementos. TurtleWoW specific." },
    { action="collect", quest=41037, name="Rods for the Pellars", item="Foulhide Talisman", coords={x=32.7,y=35.4}, note="Kill Foulhide Gnolls to pick up Foulhide Talismans. TurtleWoW specific." },
    { action="kill", quest=41035, name="The Hound and the Hunter", mob="Matthew Beckett", coords={x=49.9,y=29.0}, note="TurtleWoW specific." },
    { action="collect", quest=41034, name="A Vile Mantle", item={"Vilewing Pelt","Duskpelt Fur"}, coords={x=53.0,y=41.9}, note="Kill Vilewing Bats and Duskpelt wolves to pick up Vilewing Pelts and Duskpelt Furs. TurtleWoW specific." },
    { action="turnin", quest=41034, name="A Vile Mantle", npc="Bearbane", coords={x=46.6,y=46.8}, note="TurtleWoW specific." },
    { action="turnin", quest=41035, name="The Hound and the Hunter", npc="Levandra", coords={x=45.7,y=46.0}, note="TurtleWoW specific." },
    { action="turnin", quest=41037, name="Rods for the Pellars", npc="Mustang", coords={x=45.7,y=43.7}, note="TurtleWoW specific." },
    { action="turnin", quest=40907, name="The Haunting of Aliattan Anderson", npc="Lurn Five-Pelts", coords={x=42.6,y=43.4}, note="TurtleWoW specific." },
    { action="accept", quest=40908, name="The Black Waltz", npc="Lurn Five-Pelts", coords={x=42.6,y=43.4}, note="TurtleWoW specific." },
    { action="turnin", quest=41036, name="Deathly Fetters", npc="Lurn Five-Pelts", coords={x=42.6,y=43.4}, note="TurtleWoW specific." },
    { action="kill", quest=40908, name="The Black Waltz", mob="Willow", coords={x=39.2,y=55.4}, note="Click Aliattan's camp fire to spawn Willow. TurtleWoW specific." },
    { action="turnin", quest=40907, name="The Black Waltz", npc="Aliattan Anderson", coords={x=50.3,y=47.9}, note="TurtleWoW specific." },
    { action="accept", quest=40830, name="Scouring Greyshire", npc="Father Oblen", coords={x=33.7,y=54.1}, note="TurtleWoW specific." },
    { action="accept", quest=40945, name="Snarlclaw", npc="Maxwell Givings", coords={x=33.2,y=53.4}, note="TurtleWoW specific." },
    { action="accept", quest=40928, name="Foulhide Pests", npc="Darrow Shademore", coords={x=33.3,y=53.3}, note="TurtleWoW specific." },
    { action="turnin", quest=40933, name="Rosewick Worries", npc="Frell Rosewick", coords={x=33.1,y=54.0}, note="She is upstairs. TurtleWoW specific." },
    { action="accept", quest=40934, name="Allies Against Undeath", npc="Brother Elias", coords={x=33.5,y=54.2}, note="He is upstairs. TurtleWoW specific." },
    { action="collect", quest=40830, name="Scouring Greyshire", item="Greyshire Manuscripts", coords={x=36.3,y=46.0}, note="Click Weathered Chest to pick up Greyshire Manuscripts. TurtleWoW specific." },
    { action="kill", quest=40934, name="Allies Against Undeath", mob={"Lingering Skeleton","Shambling Dead"}, coords={x=36.6,y=47.4}, note="TurtleWoW specific." },
    { action="info", name="Snarlclaw", note="Enter the cave. Optional: Only if grouped.", coords={x=40.5,y=39.7} },
    { action="collect", quest=40945, name="Snarlclaw", item="Snarlclaw's Mane", coords={x=41.3,y=45.0}, note="Kill Snarlclaw to pick up Snarlclaw's Mane. Optional: Only if grouped. TurtleWoW specific." },
    { action="collect", quest=40928, name="Foulhide Pests", item="Foulhide Armband", coords={x=41.8,y=61.5}, note="Kill Foulhide Gnolls to pick up Foulhide Armbands. TurtleWoW specific." },
    { action="turnin", quest=40830, name="Scouring Greyshire", npc="Father Oblen", coords={x=33.7,y=54.1}, note="TurtleWoW specific." },
    { action="turnin", quest=40945, name="Snarlclaw", npc="Maxwell Givings", coords={x=33.2,y=53.4}, note="If not completed, abandon this Quest. TurtleWoW specific." },
    { action="turnin", quest=40928, name="Foulhide Pests", npc="Darrow Shademore", coords={x=33.3,y=53.3}, note="TurtleWoW specific." },
    { action="turnin", quest=40934, name="Allies Against Undeath", npc="Brother Elias", coords={x=33.5,y=54.2}, note="He is upstairs. TurtleWoW specific." },
    --{ action="accept", quest=40935, name="Scarlet Corruption", npc="Brother Elias", coords={x=33.5,y=54.2}, note="TurtleWoW specific." },
    { action="accept", quest=41032, name="To Numb the Pain", npc="Mother Tanya", coords={x=32.9,y=75.6}, note="Down in the crypt. TurtleWoW specific." },
    --{ action="accept", quest=41112, name="Ravencroft's Ambition", npc="Ethan Ravencroft", coords={x=33.1,y=76.0}, note="TurtleWoW specific." },
    --{ action="accept", quest=41033, name="A Bloody Solution", npc="Ethan Ravencroft", coords={x=33.1,y=76.0}, note="TurtleWoW specific." },
    { action="collect", quest=41032, name="To Numb the Pain", item="Hollow Web Venom", coords={x=41.0,y=75.1}, note="Kill Hollow Web Spiders to pick up Hollow Web Venom. TurtleWoW specific." },
    { action="turnin", quest=41032, name="To Numb the Pain", npc="Mother Tanya", coords={x=32.9,y=75.6}, note="Down in the crypt. TurtleWoW specific." },
    { action="accept", quest=40940, name="Font of Arcana", npc="Magus Orelius", coords={x=57.7,y=68.6}, note="TurtleWoW specific." },
    { action="turnin", quest=40944, name="Onward to Ravenshire", npc="Clerk Ebonmere", coords={x=57.7,y=68.1}, note="TurtleWoW specific." },
    { action="accept", quest=40967, name="Ravenwood Keep", npc="Lord Darius Ravenwood", coords={x=58.4,y=67.6}, note="TurtleWoW specific." },
    { action="accept", quest=40972, name="The Rebellion", npc="Lord Darius Ravenwood", coords={x=58.4,y=67.6}, note="TurtleWoW specific." },
    { action="info", quest=40972, name="The Rebellion", coords={x=58.4,y=67.6}, note="Click through Lord Darius Ravenwood's story. TurtleWoW specific." },
    { action="turnin", quest=40972, name="The Rebellion", npc="Lord Darius Ravenwood", coords={x=58.4,y=67.6}, note="TurtleWoW specific." },
    --{ action="accept", quest=40966, name="The Deed to Ravenshire", npc="Baron Caliban Silverlaine", coords={x=58.4,y=67.8}, note="TurtleWoW specific." },
    { action="accept", quest=40948, name="Wolf Amongst Sheep", npc="Baron Caliban Silverlaine", coords={x=58.4,y=67.8}, note="TurtleWoW specific." },
    { action="accept", quest=40924, name="Signet of Silverlaine", npc="Baron Caliban Silverlaine", coords={x=58.4,y=67.8}, note="TurtleWoW specific." },
    { action="accept", quest=40926, name="Securing Gilneas I", npc="Corporal Ranworth", coords={x=59.5,y=72.6}, note="TurtleWoW specific." },
    { action="accept", quest=40946, name="Spitecrest Incursions", npc="Dockwatcher Vorren", coords={x=62.0,y=73.3}, note="TurtleWoW specific." },
    { action="info", name="Get Flight Path", note="Get the Ravenshire Flight Path.", coords={x=62.0,y=74.0} },
    { action="kill", quest=40967, name="Ravenwood Keep", mob={"Sergeant Gately","Custodian Mathias","Ravenwood Apparition","Ravenwood Spectre"}, coords={x=59.3,y=82.8}, note="Optional: Only if grouped. TurtleWoW specific." },
    { action="turnin", quest=40967, name="Ravenwood Keep", npc="Lord Darius Ravenwood", coords={x=58.4,y=67.6}, note="TurtleWoW specific." },
    { action="accept", quest=40853, name="The Staff of Shinban", npc="Sergeant Arbington", coords={x=57.6,y=72.9}, note="TurtleWoW specific." },
    { action="accept", quest=40852, name="Brol'ok Ogre Bounty", npc="Sergeant Arbington", coords={x=57.6,y=72.9}, note="TurtleWoW specific." },
    { action="accept", quest=40965, name="Feeding the Rebellion", npc="Narwick Everton", coords={x=57.0,y=74.1}, note="TurtleWoW specific." },
    { action="accept", quest=40925, name="Hollow Web Silk", npc="Magistrate Carson", coords={x=59.1,y=76.1}, note="TurtleWoW specific." },
    { action="collect", quest=40965, name="Feeding the Rebellion", item="Greater Vilewing Meat", coords={x=54.0,y=86.4}, note="Kill Greater Vilewing Bats to collect Greater Vilewing Meat. TurtleWoW specific." },
    { action="collect", quest=40946, name="Spitecrest Incursions", item="Spitecrest Scale", coords={x=55.5,y=93.1}, note="Kill Spitecrest Naga to pick up Spitecrest Scales. TurtleWoW specific." },
    { action="collect", quest=40925, name="Hollow Web Silk", item="Hollow Web Silk", coords={x=41.0,y=75.1}, note="Kill Hollow Web Spiders to pick up Hollow Web Silk. TurtleWoW specific." },
    { action="collect", quest=40924, name="Signet of Silverlaine", item="Signet of Silverlaine", coords={x=20.2,y=61.0}, note="Kill High Officer Osmark to pick up Signet of Silverlaine. TurtleWoW specific." },
    { action="info", name="Wolf Amongst Sheep", note="Enter the mine.", coords={x=19.9,y=45.2} },
    { action="turnin", quest=40948, name="Wolf Amongst Sheep", npc="Liam Greymane", coords={x=25.3,y=43.7}, note="TurtleWoW specific." },
    { action="accept", quest=40949, name="One Chain at a Time", npc="Liam Greymane", coords={x=25.3,y=43.7}, note="TurtleWoW specific." },
    { action="collect", quest=40949, name="One Chain at a Time", item="Rust-Covered Key", coords={x=18.1,y=44.3}, note="Kill Guard Captain Marson to pick up Rust-Covered Key. TurtleWoW specific." },
    { action="turnin", quest=40949, name="One Chain at a Time", npc="Liam Greymane", coords={x=25.3,y=43.7}, note="TurtleWoW specific." },
    { action="accept", quest=40950, name="On Legend's Trail", npc="Liam Greymane", coords={x=25.3,y=43.7}, note="TurtleWoW specific." },
    { action="collect", quest=40926, name="Securing Gilneas I", item="Bloodclaw Pelt", coords={x=41.1,y=39.0}, note="Kill Bloodclaw Worgen to pick up Bloodclaw Pelts. TurtleWoW specific." },
    { action="turnin", quest=40950, name="On Legend's Trail", npc="Tess Greymane", coords={x=44.1,y=43.1}, note="TurtleWoW specific." },
    { action="accept", quest=40951, name="Back to Ravenshire", npc="Tess Greymane", coords={x=44.1,y=43.1}, note="TurtleWoW specific." },
    { action="collect", quest=40853, name="The Staff of Shinban", item="Staff of Shinban", coords={x=53.9,y=64.2}, note="Kill Shinban Four-Eyes to pick up Staff of Shinban. He is in the cave. TurtleWoW specific." },
    { action="collect", quest=40852, name="Brol'ok Ogre Bounty", item="Brol'ok Ogre Head", coords={x=53.1,y=62.1}, note="Kill Brol'ok Ogres to pick up Brol'ok Ogre Heads. TurtleWoW specific." },
    { action="turnin", quest=40924, name="Signet of Silverlaine", npc="Baron Caliban Silverlaine", coords={x=58.4,y=67.8}, note="TurtleWoW specific." },
    { action="turnin", quest=40951, name="Back to Ravenshire", npc="Liam Greymane", coords={x=58.5,y=68.0}, note="TurtleWoW specific." },
    { action="accept", quest=40952, name="Dim Light in the Darkness", npc="Liam Greymane", coords={x=58.5,y=68.0}, note="TurtleWoW specific." },
    { action="turnin", quest=40926, name="Securing Gilneas I", npc="Corporal Ranworth", coords={x=59.5,y=72.6}, note="TurtleWoW specific." },
    { action="accept", quest=40927, name="Securing Gilneas II", npc="Corporal Ranworth", coords={x=59.5,y=72.6}, note="TurtleWoW specific." },
    { action="turnin", quest=40946, name="Spitecrest Incursions", npc="Dockwatcher Vorren", coords={x=62.0,y=73.3}, note="TurtleWoW specific." },
    { action="accept", quest=40947, name="Spitecrest Decursions", npc="Dockwatcher Vorren", coords={x=62.0,y=73.3}, note="TurtleWoW specific." },   
    { action="turnin", quest=40852, name="Brol'ok Ogre Bounty", npc="Sergeant Arbington", coords={x=57.6,y=72.9}, note="TurtleWoW specific." },
    { action="turnin", quest=40853, name="The Staff of Shinban", npc="Sergeant Arbington", coords={x=57.6,y=72.9}, note="TurtleWoW specific." },
    { action="turnin", quest=40965, name="Feeding the Rebellion", npc="Narwick Everton", coords={x=57.0,y=74.1}, note="TurtleWoW specific." },
    { action="turnin", quest=40925, name="Hollow Web Silk", npc="Magistrate Carson", coords={x=59.1,y=76.1}, note="TurtleWoW specific." },
    { action="kill", quest=40947, name="Spitecrest Decursions", mob="Lord Zarsan", coords={x=59.4,y=93.6}, note="TurtleWoW specific." },
    { action="kill", quest=40947, name="Spitecrest Decursions", mob="Mistress Hesszha", coords={x=31.4,y=78.2}, note="TurtleWoW specific." }, 
    { action="turnin", quest=40952, name="Dim Light in the Darkness", npc="Moranna Rosenberg", coords={x=32.7,y=75.4}, note="Down in the crypt. TurtleWoW specific." },  
    { action="accept", quest=40953, name="Vilest of Men", npc="Moranna Rosenberg", coords={x=32.7,y=75.4}, note="TurtleWoW specific." },  
    { action="collect", quest=40953, name="Vilest of Men", item="Vial of Blood", coords={x=20.2,y=62.0}, note="Kill Greymanes to pick up Vials of Blood. TurtleWoW specific." },
    { action="turnin", quest=40953, name="Vilest of Men", npc="Moranna Rosenberg", coords={x=32.7,y=75.4}, note="Down in the crypt. TurtleWoW specific." },  
    { action="accept", quest=40954, name="A Crossroads Deal", npc="Moranna Rosenberg", coords={x=32.7,y=75.4}, note="TurtleWoW specific." }, 
    { action="kill", quest=40927, name="Securing Gilneas II", mob="Bloodclaw Alpha", coords={x=40.8,y=40.2}, note="In the cave. TurtleWoW specific." },
    { action="turnin", quest=40954, name="A Crossroads Deal", npc="Liam Greymane", coords={x=58.5,y=68.0}, note="TurtleWoW specific." }, 
    { action="accept", quest=40955, name="Assaulting Freyshear Keep", npc="Liam Greymane", coords={x=58.5,y=68.0}, note="TurtleWoW specific." }, 
    { action="turnin", quest=40927, name="Securing Gilneas II", npc="Corporal Ranworth", coords={x=59.5,y=72.6}, note="TurtleWoW specific." },
    { action="turnin", quest=40947, name="Spitecrest Decursions", npc="Dockwatcher Vorren", coords={x=62.0,y=73.3}, note="TurtleWoW specific." },   
    { action="info", name="Assaulting Freyshear Keep", note="Cross the bridge.", coords={x=58.6,y=53.3} },
    { action="accept", quest=40929, name="The Gilneas Lighthouse", npc="Elaroth Ranworth", coords={x=65.0,y=57.0}, note="TurtleWoW specific." }, 
    { action="kill", quest=40955, name="Assaulting Freyshear Keep", mob={"Greymane Preserver","Cannoneer Rileson"}, coords={x=66.6,y=65.6}, note="TurtleWoW specific." }, 
    { action="turnin", quest=40955, name="Assaulting Freyshear Keep", npc="Lord Darius Ravenwood", coords={x=58.4,y=67.6}, note="TurtleWoW specific." }, 
    { action="info", name="Gadgetzan", note="Use Hearthstone to return to Gadgetzan.", coords={x=62.0,y=73.3} },
    { nextGuide = "Feralas 46-48.lua" }
    --{ action="accept", quest=40975, name="The Judge and the Phantom", npc="Angered Phantom", coords={x=52.5,y=28.5}, note="TurtleWoW specific." },
  }
}