LevelingGuide_Hillsbrad = {
  steps = {
     { action="turnin", quest=647, name="MacKreel's Moonshine", npc="Brewmeister Bilger", coords={x=52.1,y=58.7}, note="He is in the basement." },
     { action="accept", quest=555, name="Soothing Turtle Bisque", npc="Chef Jessen", coords={x=51.9,y=58.6} },
     { action="accept", quest=536, name="Down the Coast", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="info", name="Get Flight Path", note="Get the Hillsbrad Flight Path.", coords={x=49.3,y=52.3} },
     { action="turnin", quest=538, name="Southshore", npc="Loremaster Dibbs", coords={x=50.5,y=57.0} },
     { action="kill", quest=536, name="Down the Coast", mob={"Torn Fin Tidehunter", "Torn Fin Oracle"}, coords={x=41.1,y=67.9} },
     { action="turnin", quest=536, name="Down the Coast", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="accept", quest=559, name="Farren's Proof", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="collect", quest=559, name="Farren's Proof", item="Murloc Head", coords={x=41.1,y=67.9}, note="Kill Torn Fin Murlocs to pick up their heads." },
     { action="turnin", quest=559, name="Farren's Proof", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="accept", quest=560, name="Farren's Proof", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="turnin", quest=560, name="Farren's Proof", npc="Marshal Redpath", coords={x=49.5,y=58.7} },
     { action="accept", quest=561, name="Farren's Proof", npc="Marshal Redpath", coords={x=49.5,y=58.7} },
     { action="turnin", quest=561, name="Farren's Proof", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="accept", quest=562, name="Stormwind Ho!", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="kill", quest=562, name="Stormwind Ho!", mob={"Daggerspine Shorehunter","Daggerspine Siren"}, coords={x=57.8,y=69.1} },
     { action="turnin", quest=562, name="Stormwind Ho!", npc="Lieutenant Farren Orinelle", coords={x=51.5,y=58.4} },
     { action="info", name="Teleport to Menethil", note="Use Hearthstone to Menethil.", coords={x=10.7,y=60.9}},
     { action="info", name="Boat to Theramore", note="Get on the boat to Theramore.", coords={x=10.6,y=60.7}},
     { action="info", name="Get Flight Path", note="Get the Theramore Flight Path.", coords={x=67.5,y=51.3} },
     { action="accept", quest=1282, name="They Call Him Smiling Jim", npc="Guard Byron", coords={x=66.2,y=46.0} },
     { action="accept", quest=1135, name="Highperch Venom", npc="Fiora Longears", coords={x=66.5,y=45.1}, note="She is inside the inn." },
     { action="turnin", quest=1264, name="The Missing Diplomat", npc="Commander Samaul", coords={x=68.0,y=48.7}, note="He is up the inn."  },
     { action="accept", quest=1265, name="The Missing Diplomat", npc="Commander Samaul", coords={x=68.0,y=48.7} },
     { action="turnin", quest=1282, name="They Call Him Smiling Jim", npc="Captain Garran Vimes", coords={x=68.2,y=48.6} },
     { action="turnin", quest=1265, name="The Missing Diplomat", npc="Archmage Tervosh", coords={x=59.7,y=41.1} },
     { action="accept", quest=1266, name="The Missing Diplomat", npc="Archmage Tervosh", coords={x=59.7,y=41.1} },
     { action="accept", quest=40416, name="Delivery to Cross", npc="Captain Wallace Cross", coords={x=59.7,y=41.1}, note="TurtleWoW specific." },
     { action="turnin", quest=1266, name="The Missing Diplomat", npc="Private Hendel", coords={x=45.3,y=24.7} },
     { action="accept", quest=1248, name="Suspicious Hoofprints", npc="Hoofprints", coords={x=29.7,y=47.6}, note="Outside the inn." },
     { action="accept", quest=1252, name="Lieutenant Paval Reethe", npc="Theramore Guard Badge", coords={x=29.8,y=48.2}, note="Click the Theramore Guard Badge inside the inn on the wooden plank." },
     { action="accept", quest=1252, name="The Black Shield", npc="Black Shield", coords={x=29.6,y=48.6}, note="Click the Black Shield inside the inn on the brick chimney." },
     { action="turnin", quest=1947, name="Journey to the Marsh", npc="Tabetha", coords={x=46.0,y=57.1} },
     { action="accept", quest=1949, name="Hidden Secrets", npc="Tabetha", coords={x=46.0,y=57.1} },
     { action="info", name="Southern Barrens", note="Go to the Southern Barrens.", coords={x=28.5,y=47.2} },
     { action="info", name="Thousand Needles", note="Go to Thousand Needles.", coords={x=44.2,y=91.4} },
     { action="info", name="Henrig Lonebrow's Journal", note="Pick up Henrig Lonebrow's Journal.", coords={x=30.7,y=24.4} },
     { action="accept", quest=1100, name="Lonebrow's Journal", npc="Henrig Lonebrow's Journal", coords={x=30.7,y=24.4}, note="Click Henrig Lonebrow's Journal in your inventory to accept this Quest." },
     { action="info", name="Thalanaar", note="Go to Thalanaar.", coords={x=8.4,y=18.8} },
     { action="turnin", quest=1100, name="Lonebrow's Journal", npc="Falfindel Waywarder", coords={x=89.6,y=46.6} },
     { action="info", name="Get Flight Path", note="Get the Thalanaar Flight Path.", coords={x=89.5,y=45.8} },
     { action="collect", quest=1135, name="Highperch Venom", item="Highperch Venom Sac", coords={x=11.7,y=34.0}, note="Kill Highperch Wyverns to collect Highperch Venom Sacs." },
     { nextGuide = "Thousand Needles 31-32.lua" },
    }
}
     