LevelingGuide_LapidisIsle = {
  steps = {
    { action="accept", quest=40093, name="The Tidemaster", npc="Deckmaster Breachcrest", coords={x=62.4,y=41.1}, note="TurtleWoW specific." },
    --{ action="accept", quest=40141, name="The Boran Family", npc="Arnold Boran", coords={x=61.6,y=43.6}, note="TurtleWoW specific." },
    { action="accept", quest=40142, name="Sailors Innovation", npc="'Slim'", coords={x=61.5,y=44.6}, note="TurtleWoW specific." },
    { action="accept", quest=40152, name="Faelon's Folly", npc="Devon Harkwave", coords={x=61.0,y=43.6}, note="He is upstairs. TurtleWoW specific." },
    --{ action="accept", quest=40148, name="Southsea Reserve", npc="Sailor Larson", coords={x=60.2,y=45.3}, note="TurtleWoW specific." },
    --{ action="accept", quest=40151, name="The Aqua Stone", npc="Hydromancer Vanessa", coords={x=59.0,y=43.3}, note="TurtleWoW specific." },
    { action="collect", quest=40093, name="The Tidemaster", item="Tidemaster Logbook", coords={x=60.3,y=24.0}, note="Click Kul Tiran Trunk to pick up Tidemaster Logbook. Underwater in the ship. TurtleWoW specific." },
    { action="accept", quest=40092, name="Lost and Stranded", npc="Wally Burnside", coords={x=56.3,y=8.9}, note="TurtleWoW specific." },
    { action="kill", quest=40092, name="Lost and Stranded", mob={"Wallowfin Murloc","Rusted Compass"}, coords={x=61.4,y=13.7}, note="Click Cracked Crate to pick up Rusted Compass. TurtleWoW specific." },
    { action="collect", quest=40142, name="Sailors Innovation", item="Juicy Crawler Leg", coords={x=55.6,y=15.7}, note="Kill Crabs to pick up Juicy Crawler Legs. TurtleWoW specific." },
    { action="turnin", quest=40092, name="Lost and Stranded", npc="Wally Burnside", coords={x=56.3,y=8.9}, note="TurtleWoW specific." },
    { action="turnin", quest=40093, name="The Tidemaster", npc="Deckmaster Breachcrest", coords={x=62.4,y=41.1}, note="TurtleWoW specific." },
    { action="info", quest=40142, name="Sailors Innovation", coords={x=60.3,y=44.3}, note="Talk to Chef Jenkel to receive Pinch of Salt." },
    { action="turnin", quest=40142, name="Sailors Innovation", npc="'Slim'", coords={x=61.5,y=44.6}, note="TurtleWoW specific." },
    { action="accept", quest=40155, name="The Gor'dosh Ogres", npc="Sergeant Blackwell", coords={x=58.3,y=42.3}, note="TurtleWoW specific." },
    { action="kill", quest=40155, name="The Gor'dosh Ogres", mob={"Gor'dosh Brute","Gor'dosh Ogre","Gor'dosh Shaman"}, coords={x=43.3,y=36.2}, note="TurtleWoW specific." },
    { action="turnin", quest=40155, name="The Gor'dosh Ogres", npc="Sergeant Blackwell", coords={x=58.3,y=42.3}, note="TurtleWoW specific." },
    { action="accept", quest=40156, name="The Tyrant King", npc="Sergeant Blackwell", coords={x=58.3,y=42.3}, note="TurtleWoW specific." },
    { action="collect", quest=40156, name="The Tyrant King", item="Tyrant's Crown", coords={x=34.4,y=27.2}, note="Kill Tyrant King Brog'dosh to pick up Tyrant's Crown. He is in the cave. TurtleWoW specific." },
    { action="turnin", quest=40156, name="The Tyrant King", npc="Sergeant Blackwell", coords={x=58.3,y=42.3}, note="TurtleWoW specific." },
    { action="accept", quest=40094, name="The Water Rat", npc="Sergeant Blackwell", coords={x=58.3,y=42.3}, note="TurtleWoW specific." },
    { action="accept", quest=40150, name="Drowning Deeptide", npc="Eliza Caldwell", coords={x=58.1,y=40.9}, note="TurtleWoW specific." },
    { action="collect", quest=40094, name="The Water Rat", item="Head of Jorgy", coords={x=34.8,y=53.0}, note="Kill 'Water Rat' Jorgy to pick up Head of Jorgy. TurtleWoW specific." },
    { action="accept", quest=40149, name="The Rotten Renown", npc="Waterlogged Trunk", coords={x=27.4,y=63.4}, note="Click Waterlogged Trunk to accept this Quest. Underwater on the first floor of the ship. TurtleWoW specific." },
    { action="collect", quest=40151, name="The Aqua Stone", item="Aqua Stone", coords={x=28.2,y=79.9}, note="Optional: Grouped only. Kill Hargul the Hardy to pick up Aqua Stone. TurtleWoW specific." },
    { action="turnin", quest=40094, name="The Water Rat", npc="Sergeant Blackwell", coords={x=58.3,y=42.3}, note="TurtleWoW specific." },
    { action="turnin", quest=40151, name="The Aqua Stone", npc="Hydromancer Vanessa", coords={x=59.0,y=43.3}, note="TurtleWoW specific." },
    { action="turnin", quest=40149, name="The Rotten Renown", npc="Colonel Hardinus", coords={x=61.2,y=41.4}, note="TurtleWoW specific." },
    { action="accept", quest=40163, name="The Tower of Lapidis", npc="Colonel Hardinus", coords={x=61.2,y=41.4}, note="TurtleWoW specific." },
    { action="accept", quest=40143, name="Smashing the Southsea!", npc="Colonel Hardinus", coords={x=61.2,y=41.4}, note="TurtleWoW specific." },
    { action="turnin", quest=40163, name="The Tower of Lapidis", npc="Hydromancer Flakereef", coords={x=59.2,y=43.8}, note="TurtleWoW specific." },
    { action="accept", quest=40164, name="The Tower of Lapidis II", npc="Hydromancer Flakereef", coords={x=59.2,y=43.8}, note="TurtleWoW specific." },
    { action="accept", quest=40160, name="Bengal Fangs", npc="Primalist Palaz", coords={x=51.9,y=51.9}, note="TurtleWoW specific." },
    { action="accept", quest=40161, name="Hazu Leaf", npc="Primalist Yango", coords={x=53.1,y=52.5}, note="TurtleWoW specific." },
    { action="collect", quest=40160, name="Bengal Fangs", item="Bengal Fang", coords={x=65.2,y=60.9}, note="Kill Bengal Tigers to pick up Bengal Fangs. TurtleWoW specific." },
    { action="collect", quest=40161, name="Hazu Leaf", item="Hazu Leaf", coords={x=57.5,y=62.7}, note="Click Hazu Leaf bushes to pick up Hazu Leaves. TurtleWoW specific." },
    { action="turnin", quest=40161, name="Hazu Leaf", npc="Primalist Yango", coords={x=53.1,y=52.5}, note="TurtleWoW specific." },
    { action="turnin", quest=40160, name="Bengal Fangs", npc="Primalist Palaz", coords={x=51.9,y=51.9}, note="TurtleWoW specific." },
    --{ action="accept", quest=40157, name="Hazzuri Dark Vessels", npc="Primalist Jongi", coords={x=52.9,y=50.6}, note="TurtleWoW specific." },
    --{ action="accept", quest=40158, name="Thunderhead Horn", npc="Head-Primalist Manaz'ago", coords={x=52.7,y=49.6}, note="He is upstairs. TurtleWoW specific." },
    { action="info", name="Gillijim's Isle", note="Go to Gillijim's Isle.", coords={x=46.1,y=92.7} },
    { action="collect", quest=40143, name="Smashing the Southsea!", item="Southsea Sash", coords={x=23.0,y=21.4}, note="Kill Southsea pirates to pick up Southsea Sashes. TurtleWoW specific." },
    { action="kill", quest=40152, name="Faelon's Folly", mob={"Forgotten Swordsman","Drowned Soul","Forgotten Crew"}, coords={x=38.6,y=54.4}, note="TurtleWoW specific." },
    { action="accept", quest=40153, name="An Extravagant Book", npc="Half Buried Barrel", coords={x=36.9,y=55.6}, note="Click Half Buried Barrel to accept this Quest. TurtleWoW specific." },
    { action="accept", quest=40162, name="The Evil Deeptide", npc="Smallgill", coords={x=47.4,y=75.4}, note="TurtleWoW specific." },
    { action="collect", quest=40150, name="Drowning Deeptide", item="Deeptide Bracelet", coords={x=31.8,y=87.8}, note="Kill Deeptide Naga to pick up Deeptide Bracelets. TurtleWoW specific." },
    { action="collect", quest=40162, name="The Evil Deeptide", item="Lovely Shell Necklace", coords={x=49.8,y=81.9}, note="Kill Deeptide Murlocs to pick up Lovely Shell Necklaces. TurtleWoW specific." },
    { action="turnin", quest=40162, name="The Evil Deeptide", npc="Smallgill", coords={x=47.4,y=75.4}, note="TurtleWoW specific." },
    { action="accept", quest=40210, name="The Hermit", npc="Insom'ni", coords={x=56.2,y=16.2}, note="TurtleWoW specific." }, 
    { action="turnin", quest=40210, name="The Hermit", npc="Insom'ni", coords={x=56.2,y=16.2}, note="Talk to Insom'ni, wait for RPG, then turn-in the Quest. TurtleWoW specific." }, 
    { action="info", name="Lapidis Isle", note="Go to Lapidis Isle.", coords={x=50.7,y=7.1}, note="TurtleWoW specific." },
    { action="turnin", quest=40152, name="Faelon's Folly", npc="Devon Harkwave", coords={x=61.0,y=43.6}, note="He is upstairs. TurtleWoW specific." },
    { action="turnin", quest=40143, name="Smashing the Southsea!", npc="Colonel Hardinus", coords={x=61.2,y=41.4}, note="TurtleWoW specific." },
    { action="turnin", quest=40150, name="Drowning Deeptide", npc="Eliza Caldwell", coords={x=58.1,y=40.9}, note="TurtleWoW specific." },
    { action="turnin", quest=40153, name="An Extravagant Book", npc="Father Benofar", coords={x=57.1,y=43.1}, note="TurtleWoW specific." },
    { action="info", name="Booty Bay", note="Fly to Booty Bay.", coords={x=60.2,y=43.0}, note="TurtleWoW specific." },
    { action="info", name="Ratchet", note="Take the boat to Ratchet.", coords={x=26.1,y=73.2} },
    { action="info", name="Tanaris", note="Fly to Gadgetzan.", coords={x=63.1,y=37.2} },
    { nextGuide = "Tanaris 51-52.lua" }
    }
}