LevelingGuide_SearingGorge = {
  steps = {
    { action="accept", quest=4449, name="Caught!", npc="Wooden Outhouse", coords={x=65.5,y=62.0}, note="Click Wooden Outhouse to accept this Quest." },
    { action="kill", quest=4449, name="Caught!", mob="Dark Iron Geologist", coords={x=63.2,y=59.2} },
    { action="turnin", quest=4449, name="Caught!", npc="Wooden Outhouse", coords={x=65.5,y=62.0} },
    { action="accept", quest=3367, name="Suntara Stones", npc="Dorius Stonetender", coords={x=63.9,y=61.0} },
    { action="info", note="Escort Dorius Stonetender. In the middle of the escort, a group of 4 dwarves will attack.", coords={x=74.5,y=19.4} },
    { action="turnin", quest=3367, name="Suntara Stones", npc="Dorius Stonetender", coords={x=74.5,y=19.4}, note="Click Signed Letter on the ground to turn-in the Quest." },
    { action="accept", quest=3368, name="Suntara Stones", npc="Singed Letter", coords={x=74.5,y=19.4} },
    { action="accept", quest=3441, name="Divine Retribution", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="turnin", quest=3441, name="Divine Retribution", npc="Kalaran Windblade", coords={x=39.0,y=39.0}, note="Talk Kalaran Windblade and click through the dialogue." },
    { action="accept", quest=3442, name="The Flawless Flame", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="accept", quest=7701, name="WANTED: Overseer Maltorius", npc="Wanted Poster", coords={x=37.6,y=26.5} },
    { action="accept", quest=7729, name="JOB OPPORTUNITY: Culling the Competition", npc="Help Wanted", coords={x=37.6,y=26.5} },
    { action="accept", quest=7723, name="Curse These Fat Fingers", npc="Hansel Heavyhands", coords={x=38.4,y=27.7} },
    { action="accept", quest=7724, name="Fiery Menace!", npc="Hansel Heavyhands", coords={x=38.4,y=27.7} },
    { action="accept", quest=7727, name="Incendosaurs? Whateverosaur is More Like It", npc="Hansel Heavyhands", coords={x=38.4,y=27.7} },
    { action="accept", quest=7722, name="What the Flux?", npc="Master Smith Burninate", coords={x=38.8,y=28.5} },
    { action="info", name="Get Flight Path", note="Get the Thorium Point Flight Path.", coords={x=37.9,y=30.9} },
    { action="kill", quest=7723, name="Curse These Fat Fingers", mob="Heavy War Golem", coords={x=40.1,y=42.9} },
    { action="kill", quest=7724, name="Fiery Menace!", mob="Greater Lava Spider", coords={x=29.8,y=44.3} },
    { action="collect", quest=3442, name="The Flawless Flame", item={"Heart of Flame","Golem Oil"}, coords={x=31.2,y=44.6}, note="Kill Elementals for Heart of Flame and Heavy War Golems for Golem Oil." },
    { action="turnin", quest=3442, name="The Flawless Flame", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="accept", quest=3443, name="Forging the Shaft", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="turnin", quest=7723, name="Curse These Fat Fingers", npc="Hansel Heavyhands", coords={x=38.4,y=27.7} },
    { action="turnin", quest=7724, name="Fiery Menace!", npc="Hansel Heavyhands", coords={x=38.4,y=27.7} },
    { action="info", name="Drop down", note="Drop down and enter the cave.", coords={x=47.5,y=47.0} },
    { action="kill", quest=7727, name="Incendosaurs? Whateverosaur is More Like It", mob="Incendosaur", coords={x=50.0,y=38.8} },
    { action="info", name="Leave Cave", note="Leave the cave.", coords={x=47.5,y=47.0} },
    { action="info", name="Enter Cave", note="Enter the cave.", coords={x=49.7,y=45.6} },
    { action="collect", quest=3443, name="Forging the Shaft", item="Thorium Plated Dagger", coords={x=44.2,y=36.1}, note="Kill Dark Iron dwarves to pick up Thorium Plated Daggers." },
    { action="kill", quest=7729, name="JOB OPPORTUNITY: Culling the Competition", mob={"Dark Iron Taskmaster","Dark Iron Slaver"}, coords={x=44.2,y=36.1} },
    { action="collect", quest=7701, name="WANTED: Overseer Maltorius", item="Head of Overseer Maltorius", coords={x=41.0,y=35.7}, note="Optional: Only if grouped. Kill Overseer Maltorius to pick up Head of Overseer Maltorius." },
    { action="collect", quest=7722, name="What the Flux?", item="Secret Plans: Fiery Flux", coords={x=40.5,y=35.7}, note="Click Secret Plans: Fiery Flux behind Overseer Maltorius to them up." },
    { action="turnin", quest=7701, name="WANTED: Overseer Maltorius", npc="Lookout Captain Lolo Longstriker", coords={x=37.7,y=26.6} },
    { action="turnin", quest=7727, name="Incendosaurs? Whateverosaur is More Like It", npc="Hansel Heavyhands", coords={x=38.4,y=27.7} },
    { action="turnin", quest=7729, name="JOB OPPORTUNITY: Culling the Competition", npc="Taskmaster Scrange", coords={x=39.0,y=27.5} },
    { action="turnin", quest=7722, name="What the Flux?", npc="Master Smith Burninate", coords={x=38.8,y=28.5} },
    { action="turnin", quest=3443, name="Forging the Shaft", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="accept", quest=3452, name="The Flame's Casing", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="collect", quest=3452, name="The Flame's Casing", item="Symbol of Ragnaros", coords={x=25.0,y=31.0}, note="Optional: Only if grouped. Kill Twilight members to pick up Symbol of Ragnaros." },
    { action="turnin", quest=3452, name="The Flame's Casing", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="accept", quest=3453, name="The Torch of Retribution", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="turnin", quest=3453, name="The Torch of Retribution", npc="Kalaran Windblade", coords={x=39.0,y=39.0}, note="Wait for RPG, then turn-in the Quest." },
    { action="accept", quest=3454, name="The Torch of Retribution", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="turnin", quest=3454, name="The Torch of Retribution", item="Torch of Retribution", coords={x=39.0,y=39.0}, note="Click Torch of Retribution to turn-in the Quest." },
    { action="accept", quest=3462, name="Squire Maltrake", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="turnin", quest=3462, name="Squire Maltrake", npc="Squire Maltrake", coords={x=68.7,y=36.1} },
    { action="accept", quest=3463, name="Set Them Ablaze!", npc="Squire Maltrake", coords={x=68.7,y=36.1} },
    { action="info", note="Equip Torch of Retribution for the following Quest.", coords={x=68.7,y=36.1} },
    { action="kill", quest=3463, name="Set Them Ablaze!", mob="Northern Tower Ablaze", coords={x=33.3,y=54.5}, note="Run up and click Sentry Brazier to ablaze the Northern Tower." },
    { action="kill", quest=3463, name="Set Them Ablaze!", mob="Western Tower Ablaze", coords={x=35.7,y=60.7}, note="Run up and click Sentry Brazier to ablaze the Western Tower." },
    { action="kill", quest=3463, name="Set Them Ablaze!", mob="Southern Tower Ablaze", coords={x=44.0,y=60.9}, note="Run up and click Sentry Brazier to ablaze the Southern Tower." },
    { action="kill", quest=3463, name="Set Them Ablaze!", mob="Eastern Tower Ablaze", coords={x=50.0,y=54.7}, note="Run up and click Sentry Brazier to ablaze the Eastern Tower." },
    { action="info", note="Equip your weapon again.", coords={x=50.0,y=54.7} },
    { action="turnin", quest=3463, name="Set Them Ablaze!", npc="Kalaran Windblade", coords={x=39.0,y=39.0} },
    { action="accept", quest=3481, name="Trinkets...", npc="Hoard of the Black Dragonflight", coords={x=39.0,y=39.0}, note="Click Hoard of the Black Dragonflight to accept this Quest." },
    { action="turnin", quest=3481, name="Trinkets...", npc="Hoard of the Black Dragonflight", coords={x=39.0,y=39.0}, note="Click Hoard of the Black Dragonflight to turn-in this Quest." },
    { action="info", note="Open Hoard of the Black Dragonflight in your inventory and destroy Torch of Retribution.", coords={x=39.0,y=39.0} },
    { action="accept", quest=4451, name="The Key to Freedom", npc="Grimesilt Outhouse Key", coords={x=39.0,y=39.0}, note="Optional: If you found Grimesilt Outhouse Key, accept this Quest." },
    { action="turnin", quest=4451, name="The Key to Freedom", npc="Wooden Outhouse", coords={x=65.5,y=62.0}, note="Optional: Skip this step if you don't have this Quest." },
    { action="info", quest=3181, name="The Horn of the Beast", item="Margol's Horn", coords={x=73.0,y=75.0}, note="Kill Margol the Rager to pick up Margol's Horn." },
    { action="accept", quest=3181, name="The Horn of the Beast", npc="Margol's Horn", coords={x=73.0,y=75.0}, note="Use Margol's Horn in your inventory to accept this Quest." },
    { action="info", note="Grind nearby until Level 48.", coords={x=73.0,y=75.0} },
    { action="info", name="Hearthstone", note="Use Hearthstone to return to Thelsamar.", coords={x=73.0,y=75.0} },
    { action="turnin", quest=3181, name="The Horn of the Beast", npc="Mountaineer Pebblebitty", coords={x=18.2,y=84.0} },
    { action="accept", quest=3182, name="Proof of Deed", npc="Mountaineer Pebblebitty", coords={x=18.2,y=84.0} },
    { action="info", name="Ironforge", note="Use Teleport: Ironforge or fly to Ironforge.", coords={x=33.9,y=51.0} },
    { action="turnin", quest=3182, name="Proof of Deed", npc="Curator Thorius", coords={x=70.7,y=17.0} },
    { action="turnin", quest=3368, name="Suntara Stones", npc="Curator Thorius", coords={x=70.7,y=17.0} },
    { action="accept", quest=3371, name="Dwarven Justice", npc="Curator Thorius", coords={x=70.7,y=17.0} },
    { action="accept", quest=3201, name="At Last!", npc="Curator Thorius", coords={x=70.7,y=17.0} },
    { action="accept", quest=4512, name="A Little Slime Goes a Long Way", npc="Laris Geardawdle", coords={x=75.8,y=23.6} },
    { action="accept", quest=3448, name="Passing the Burden", npc="Historian Karnik", coords={x=77.2,y=11.8} },
    { action="turnin", quest=3448, name="Passing the Burden", npc="Tymor", coords={x=31.0,y=4.8} },
    { action="accept", quest=3449, name="Arcane Runes", npc="Tymor", coords={x=31.0,y=4.8} },
    { action="accept", quest=3450, name="An Easy Pickup", npc="Tymor", coords={x=31.0,y=4.8} },
    { action="accept", quest=3790, name="Assisting Arch Druid Staghelm", npc="Innkeeper Firebrew", coords={x=18.1,y=51.4} },
    { action="info", name="Bank", note="Deposit to Bank: Extra Cloth.", coords={x=35.5,y=60.6} },
    { action="turnin", quest=3450, name="An Easy Pickup", npc="Xiggs Fuselighter", coords={x=70.9,y=94.6} },
    { action="accept", quest=3451, name="Signal for Pickup", npc="Xiggs Fuselighter", coords={x=70.9,y=94.6} },
    { action="turnin", quest=3451, name="Signal for Pickup", npc="Xiggs Fuselighter", coords={x=70.9,y=94.6} },
    { action="info", name="Thelsamar", note="Fly to Thelsamar.", coords={x=55.5,y=47.7} },
    { action="turnin", quest=3201, name="At Last!", npc="Mountaineer Pebblebitty", coords={x=18.2,y=84.0} },
    { action="info", name="Thorium Point", note="Fly to Thorium Point.", coords={x=33.9,y=51.0} },
    { action="info", name="Drop down", note="Drop down into the cave.", coords={x=35.4,y=42.2} },
    { action="turnin", quest=3371, name="Dwarven Justice", npc="Dying Archaeologist", coords={x=41.0,y=25.5} },
    { action="turnin", quest=3371, name="Dwarven Justice", npc="Dying Archaeologist", coords={x=41.0,y=25.5} },
    { action="info", name="Leave Cave", note="Use Teleport: Stormwind or run back and open the Quarry Gate to leave the cave.", coords={x=37.7,y=44.2} },
    { action="info", name="Blasted Lands", note="Fly to Nethergarde Keep.", coords={x=37.9,y=30.9} },   
    { nextGuide = "Blasted Lands 49-50.lua" }
  }
}