LevelingGuide_Stranglethorn_4 = {
  steps = {
    { action="info", name="Bind Hearthstone", note="Bind your Hearthstone to Booty Bay at Innkeeper Skindle.", coords={x=27.0,y=77.3} },
    --{ action="turnin", quest=1118, name="Back to Booty Bay", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="info", name="Bank", note="Withdraw from Bank: Gorilla Fangs.", coords={x=26.7,y=76.4} },
    { action="accept", quest=348, name="Stranglethorn Fever", npc="Fin Fizracket", coords={x=27.6,y=76.7} },
    { action="accept", quest=8551, name="The Captain's Chest", npc="Captain Hecklebury Smotts", coords={x=26.7,y=73.6} },
    { action="collect", quest=349, name="Stranglethorn Fever", item="Heart of Mokk", coords={x=35.0,y=60.5}, note="Talk to Witch Doctor Unbagwa to turn-in your Gorilla Fangs. This will spawn three waves of Gorillas. Finally kill Mokk the Savage to pick up Heart of Mokk." },
    { action="collect", quest=8551, name="The Captain's Chest", item="Smotts' Chest", coords={x=37.0,y=70.0}, note="Kill Gorlash to pick up Smotts' Chest." },
    { action="info", name="Half-Buried Bottle", note="Run along the shoreline and look for Half-Buried Bottles. Click Half-Buried Bottles until you pick up a Carefully Folded Note. The arrow shows the most southern bottle, the most northern bottle is at 40.2, 60.2.", coords={x=34.0,y=76.8} },
    { action="accept", quest=594, name="Message in a Bottle", npc="Carefully Folded Note", coords={x=34.0,y=76.8}, note="Use the Carefully Folded Note in your inventory to accept this Quest." },
    { action="turnin", quest=594, name="Message in a Bottle", npc="Princess Poobah", coords={x=38.5,y=80.6} },
    { action="accept", quest=630, name="Message in a Bottle", npc="Princess Poobah", coords={x=38.5,y=80.6} },
    { action="collect", quest=630, name="Message in a Bottle", item="Shackle Key", coords={x=41.0,y=84.0}, note="Kill King Mukla to pick up Shackle Key." },
    { action="turnin", quest=630, name="Message in a Bottle", npc="Princess Poobah", coords={x=38.5,y=80.6} },
    { action="info", name="Hearthstone", note="Use Hearthstone to return to Booty Bay.", coords={x=38.5,y=80.6} },
    --{ action="accept", quest=1119, name="Zanzil's Mixture and a Fool's Stout", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="turnin", quest=348, name="Stranglethorn Fever", npc="Fin Fizracket", coords={x=27.6,y=76.7} },
    { action="turnin", quest=8551, name="The Captain's Chest", npc="Captain Hecklebury Smotts", coords={x=26.7,y=73.6} },
    { action="info", name="Destroy Item", note="Destroy the Carefully Folded Note in your inventory.", coords={x=26.7,y=73.6} },
    { action="info", name="Ratchet", note="Take the boat to Ratchet.", coords={x=26.0,y=73.2} },
    { action="turnin", quest=5158, name="Seeking Spiritual Aid", npc="Islen Waterseer", coords={x=65.8,y=43.8} },
    { action="accept", quest=5159, name="Cleansed Water Returns to Felwood", npc="Islen Waterseer", coords={x=65.8,y=43.8}, note="Wait for RPG, then accept the Quest." },
    { action="collect", quest=3444, name="The Stone Circle", item="Stone Circle", coords={x=62.5,y=38.5}, note="Click Marvon's Chest to pick up Stone Circle." },
    { action="accept", quest=4502, name="Volcanic Activity", npc="Liv Rizzlefix", coords={x=62.4,y=38.7} },
    { action="info", name="Theramore", note="Fly to Theramore.", coords={x=63.1,y=37.2} },
    { action="info", name="First Aid", note="Go to Doctor Gustaf VanHowzen to train First Aid.", coords={x=67.7,y=48.9} },
    { action="info", name="Gadgetzan", note="Fly to Gadgetzan.", coords={x=67.5,y=51.4} },
    { action="turnin", quest=2641, name="Sprinkle's Secret Ingredient", npc="Sprinkle", coords={x=51.1,y=26.9} },
    { action="accept", quest=2661, name="Delivery for Marin", npc="Sprinkle", coords={x=51.1,y=26.9}, note="Wait for RPG, then accept the Quest." },
    { action="turnin", quest=4493, name="March of the Silithid", npc="Alchemist Pestlezugg", coords={x=50.9,y=27.0} },
    { action="accept", quest=4496, name="Bungle in the Jungle", npc="Alchemist Pestlezugg", coords={x=50.9,y=27.0} },
    { action="turnin", quest=2661, name="Delivery for Marin", npc="Marin Noggenfogger", coords={x=51.8,y=28.6} },
    { action="accept", quest=2662, name="Noggenfogger Elixir", npc="Marin Noggenfogger", coords={x=51.8,y=28.6} },
    { action="turnin", quest=2662, name="Noggenfogger Elixir", npc="Marin Noggenfogger", coords={x=51.8,y=28.6}, note="Wait for RPG, then turn-in the Quest." },
    { action="turnin", quest=3444, name="The Stone Circle", npc="Marvon Rivetseeker", coords={x=52.7,y=45.9} },
    { action="info", name="Un'Goro Crater", note="Go to Un'Goro Crater.", coords={x=27.0,y=51.3} },
    { nextGuide = "Un'Goro Crater 54-56.lua" }
  }
}