LevelingGuide_Stranglethorn_2 = {
  steps = {
    -- In Booty Bay - Bank
    --{ action="info", name="Bank", note="Deposit to Bank: Letter of Commendation, Karnitol's Satchel", coords={x=26.7,y=76.4} },
    { action="info", name="Bank", note="Withdraw from Bank: Bloodscalp Ears, Krazek's Crock Pot, Large River Crocolisk Skin, Singing Crystal Shard", coords={x=26.7,y=76.4} },
    { action="info", name="Set Hearthstone", note="Bind your Hearthstone to Booty Bay.", coords={x=27.0,y=77.3} },
    { action="turnin", quest=605, name="Singing Blue Shards", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="accept", quest=600, name="Venture Company Mining", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="accept", quest=621, name="Zanzil's Secret", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="turnin", quest=189, name="Bloodscalp Ears", npc="Kebok", coords={x=27.0,y=77.1} },
    { action="accept", quest=213, name="Hostile Takeover", npc="Kebok", coords={x=27.0,y=77.1} },
    { action="turnin", quest=201, name="Investigate the Camp", npc="Krazek", coords={x=26.9,y=77.2} },
    { action="turnin", quest=210, name="Krazek's Cookery", npc="Krazek", coords={x=26.9,y=77.2} },
    --{ action="turnin", quest=1115, name="The Rumormonger", npc="Krazek", coords={x=26.9,y=77.2} },
    { action="turnin", quest=578, name="The Stone of the Tides", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="accept", quest=601, name="Water Elementals", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="accept", quest=1182, name="Goblin Sponsorship", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="info", name="Destroy Library Scrip", note="Destroy Library Scrip from your inventory.", coords={x=27.2,y=76.9} },
    { action="turnin", quest=575, name="Supply and Demand", npc="Drizzlik", coords={x=28.3,y=77.6} },
    { action="accept", quest=577, name="Some Assembly Required", npc="Drizzlik", coords={x=28.3,y=77.6} },
    { action="info", name="Darkshire", note="Fly to Darkshire.", coords={x=27.5,y=77.8} },
    { action="info", name="Stranglethorn", note="Go to Stranglethorn.", coords={x=44.5,y=87.4} },
    { action="accept", quest=574, name="Special Forces", npc="Sergeant Yohwa", coords={x=37.9,y=3.4} },
    { action="accept", quest=195, name="Raptor Mastery", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="accept", quest=188, name="Tiger Mastery", npc="Ajeck Rouack", coords={x=35.6,y=10.6} },
    { action="accept", quest=192, name="Panther Mastery", npc="Sir S. J. Erlgadin", coords={x=35.6,y=10.5} },
    { action="turnin", quest=328, name="The Hidden Key", npc="Bookie Herod's Strongbox", coords={x=49.6,y=7.6}, note="Take right path through the cave and then loot Bookie Herod's Strongbox near the stacks of boxes on the platform." },
    { action="accept", quest=329, name="The Spy Revealed!", npc="Bookie Herod's Strongbox", coords={x=44.0,y=9.0} },
    { action="kill", quest=574, name="Special Forces", mob={"Kurzen Commando","Kurzen Headshrinker"}, coords={x=45.5,y=8.4} },
    { action="kill", quest=192, name="Panther Mastery", mob="Shadowmaw Panther", coords={x=48.9,y=23.8} },
    { action="collect", quest=213, name="Hostile Takeover", item="Tumbled Crystal", coords={x=45.9,y=19.6}, note="Kill Venture Co. Geologists to pick up Tumbled Crystals." },
    { action="collect", quest=577, name="Some Assembly Required", item="Snapjaw Crocolisk Skin", coords={x=41.8,y=21.7}, note="Kill Snapjaw Crocolisks for Snapjaw Crocolisk Skins along the coast." },
    { action="info", quest=1182, name="Goblin Sponsorship", coords={x=42.6,y=18.3}, note="Up on the tower kill Foreman Cozzle for Cozzle's Key." },
    { action="collect", quest=1182, name="Goblin Sponsorship", item="Fuel Regulator Blueprints", coords={x=43.3,y=20.3}, note="Use Cozzle's Key to open Cozzle's Footlocker." },
    { action="kill", quest=195, name="Raptor Mastery", mob="Lashtail Raptor", coords={x=38.9,y=24.6} },
    { action="collect", quest=188, name="Tiger Mastery", item="Paw of Sin'Dall", coords={x=32.2,y=17.4}, note="Kill Sin'Dall for Paw of Sin'Dall on the hill." },
    { action="turnin", quest=195, name="Raptor Mastery", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="accept", quest=196, name="Raptor Mastery", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="turnin", quest=188, name="Tiger Mastery", npc="Ajeck Rouack", coords={x=35.6,y=10.6} },
    { action="turnin", quest=192, name="Panther Mastery", npc="Sir S. J. Erlgadin", coords={x=35.6,y=10.5} },
    { action="accept", quest=193, name="Panther Mastery", npc="Sir S. J. Erlgadin", coords={x=35.6,y=10.5} },
    { action="turnin", quest=329, name="The Spy Revealed!", npc="Lieutenant Doren", coords={x=38.0,y=3.0} },
    { action="accept", quest=330, name="Patrol Schedules", npc="Lieutenant Doren", coords={x=38.0,y=3.0} },
    { action="turnin", quest=574, name="Special Forces", npc="Lieutenant Doren", coords={x=38.0,y=3.0} },
    { action="accept", quest=202, name="Colonel Kurzen", npc="Lieutenant Doren", coords={x=38.0,y=3.0} },
    { action="turnin", quest=330, name="Patrol Schedules", npc="Corporal Sethman", coords={x=37.7,y=3.4} },
    { action="accept", quest=331, name="Report to Doren", npc="Corporal Sethman", coords={x=37.7,y=3.4} },
    { action="turnin", quest=331, name="Report to Doren", npc="Lieutenant Doren", coords={x=38.0,y=3.0} },
    { action="collect", quest=601, name="Water Elementals", item="Water Elemental Bracers", coords={x=22.2,y=23.1}, note="Kill Water Elementals for Water Elemental Bracers." },
    { action="info", name="Grind to Level 37", note="Grind nearby until Level 37.", coords={x=21.0,y=23.0} },
    { action="info", name="Booty Bay", note="Use Hearthstone to return to Booty Bay.", coords={x=21.0,y=23.0} },
    { action="turnin", quest=213, name="Hostile Takeover", npc="Kebok", coords={x=27.0,y=77.1} },
    { action="accept", quest=209, name="Skullsplitter Tusks", npc="Kebok", coords={x=27.0,y=77.1} },
    { action="turnin", quest=601, name="Water Elementals", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="accept", quest=602, name="Magical Analysis", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="turnin", quest=1182, name="Goblin Sponsorship", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="accept", quest=1183, name="Goblin Sponsorship", npc="Baron Revilgaz", coords={x=27.2,y=76.9} },
    { action="turnin", quest=577, name="Some Assembly Required", npc="Drizzlik", coords={x=28.3,y=77.6} },
    { action="accept", quest=628, name="Excelsior", npc="Drizzlik", coords={x=28.3,y=77.6} },
    { action="info", name="Bank", note="Deposit to Bank: Fuel Regulator Blueprints, Singing Blue Crystal, Stranglethorn Pages", coords={x=26.7,y=76.4} },
    { action="info", name="Bank", note="Withdraw from Bank: Farren's Report, Letter of Commendation, Decrypted Letter, Karnitol's Satchel", coords={x=26.7,y=76.4} },
    { action="info", name="Ironforge", note="Use Teleport: Ironforge or fly to Ironforge.", coords={x=27.5,y=77.8} },
    --{ action="turnin", quest=563, name="Reassignment", npc="Major Samuelson", coords={x=78.0,y=18.0} },
    --{ action="info", name="Fly to Ironforge", note="Fly from Stormwind to Ironforge.", coords={x=66.3,y=62.1} },
    --{ action="info", name="Learn Spells", note="Learn new spells from class trainers.", coords={x=30.0,y=67.0} },
    --{ action="info", name="Get Water Breathing", note="Get 2 Elixir of Water Breathing from Bank or Auction House for later.", coords={x=35.0,y=40.8} },
    --{ action="turnin", quest=1457, name="The Karnitol Shipwreck", npc="Roetten Stonehammer", coords={x=74.6,y=11.7} },
    { action="accept", quest=707, name="Ironband Wants You!", npc="Prospector Stormpike", coords={x=74.6,y=12.0} },
    { action="accept", quest=1050, name="Mythology of the Titans", npc="Librarian Mae Paledust", coords={x=74.9,y=12.6} },
    { action="info", name="Southshore", note="Fly to Southshore.", coords={x=55.5,y=47.8} },
    { action="accept", quest=659, name="Hints of a New Plague?", npc="Phin Odelic", coords={x=50.3,y=59.0} },
    { action="info", name="Set Hearthstone", note="Bind your Hearthstone to Southshore.", coords={x=51.2,y=58.9} },
    --{ action="turnin", quest=1052, name="Down the Scarlet Path", npc="Raleigh the Devout", coords={x=51.0,y=58.6} },
    --{ action="accept", quest=1053, name="In the Name of the Light", npc="Raleigh the Devout", coords={x=51.0,y=58.6} },
    { action="turnin", quest=525, name="Further Mysteries", npc="Magistrate Henry Maleb", coords={x=48.1,y=59.1} },
    { action="accept", quest=537, name="Dark Council", npc="Magistrate Henry Maleb", coords={x=48.1,y=59.1} },
    { action="accept", quest=512, name="Noble Deaths", npc="Magistrate Henry Maleb", coords={x=48.1,y=59.1} },
    { nextGuide = "Alterac 37-38.lua" },
  }
}