-- Stranglethorn 40-42 Guide
-- Based on https://www.sageguide.net/40-42_stranglethorn

LevelingGuide_Stranglethorn_3 = {
  steps = {
    { action="accept", quest=617, name="Akiris by the Bundle", npc="Privateer Bloads", coords={x=26.8,y=76.4} },
    { action="info", name="Bank", note="Withdraw from Bank: Sample Elven Gem, Singing Blue Crystals", coords={x=26.7,y=76.4} },
    { action="info", name="Set Hearthstone", note="Bind your Hearthstone to Booty Bay at Innkeeper Skindle.", coords={x=27.0,y=77.3} },
    { action="accept", quest=580, name="Whiskey Slim's Lost Grog", npc="Whiskey Slim", coords={x=27.1,y=77.5} },
    { action="turnin", quest=603, name="Ansirem's Key", npc="Catelyn the Blade", coords={x=27.3,y=77.5}, note="She is on the first floor." },
    { action="accept", quest=610, name="\"Pretty Boy\" Duncan", npc="Catelyn the Blade", coords={x=27.3,y=77.5} },
    { action="turnin", quest=669, name="Sunken Treasure", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0}, note="He is outside on the second floor." },
    { action="accept", quest=628, name="Excelsior", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0} },
    { action="accept", quest=606, name="Scaring Shaky", npc="\"Sea Wolf\" MacKinley", coords={x=27.8,y=77.1} },
    { action="accept", quest=2872, name="Stoley's Debt", npc="\"Sea Wolf\" MacKinley", coords={x=27.8,y=77.1} },
    { action="accept", quest=595, name="The Bloodsail Buccaneers", npc="First Mate Crazz", coords={x=28.1,y=76.2} },
    { action="collect", quest=610, name="\"Pretty Boy\" Duncan", item="Catelyn's Blade", coords={x=27.4,y=69.4}, note="Kill \"Pretty Boy\" Duncan to pick up Catelyn's Blade." },
    { action="turnin", quest=595, name="The Bloodsail Buccaneers", npc="Bloodsail Correspondence", coords={x=27.3,y=69.5}, note="Click Bloodsail Correspondence to turn-in Quest." },
    { action="accept", quest=597, name="The Bloodsail Buccaneers", npc="Bloodsail Correspondence", coords={x=27.3,y=69.5} },
    { action="turnin", quest=597, name="The Bloodsail Buccaneers", npc="First Mate Crazz", coords={x=28.1,y=76.2} },
    { action="accept", quest=599, name="The Bloodsail Buccaneers", npc="First Mate Crazz", coords={x=28.1,y=76.2} },
    { action="turnin", quest=610, name="\"Pretty Boy\" Duncan", npc="Catelyn the Blade", coords={x=27.3,y=77.5}, note="She is on the first floor." },
    { action="accept", quest=587, name="Up to Snuff", npc="Deeg", coords={x=26.9,y=77.3} },
    { action="turnin", quest=599, name="The Bloodsail Buccaneers", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0} },
    { action="accept", quest=604, name="The Bloodsail Buccaneers", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0} },
    { action="accept", quest=576, name="Keep An Eye Out", npc="Dizzy One-Eye", coords={x=28.6,y=75.9} },
    { action="collect", quest=606, name="Scaring Shaky", item="Mistvale Giblet", coords={x=32.9,y=66.1}, note="Kill Elder Mistvale Gorillas to pick up Mistvale Giblets. Also collect 10 Gorilla Fangs for later use." },
    { action="kill", quest=196, name="Raptor Mastery", mob="Jungle Stalker", coords={x=32.7,y=39.2} },
    { action="collect", quest=193, name="Panther Mastery", item="Fang of Bhag'thera", coords={x=49.6,y=24.0}, note="Kill Bhag'thera to pick up Fang of Bhag'thera." },
    { action="kill", quest=202, name="Colonel Kurzen", mob={"Kurzen Elite","Kurzen Subchief","Kurzen's Head"}, coords={x=49.9,y=3.9}, note="Easier to complete in a group. In the back of the cave. Kill Colonel Kurzen to pick up Kurzen's Head." },
    { action="turnin", quest=202, name="Colonel Kurzen", npc="Lieutenant Doren", coords={x=38.0,y=3.0} },
    { action="turnin", quest=193, name="Panther Mastery", npc="Sir S. J. Erlgadin", coords={x=35.6,y=10.5} },
    { action="turnin", quest=196, name="Raptor Mastery", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="accept", quest=197, name="Raptor Mastery", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="collect", quest=628, name="Excelsior", item="Elder Crocolisk Skin", coords={x=29.3,y=22.3}, note="Kill Elder Saltwater Crocolisks to pick up Elder Crocolisk Skin." },
    { action="info", name="Booty Bay", note="Use Hearthstone to return to Booty Bay.", coords={x=29.3,y=22.3} },
    { action="turnin", quest=628, name="Excelsior", npc="Drizzlik", coords={x=28.3,y=77.6} },
    { action="turnin", quest=606, name="Scaring Shaky", npc="\"Shaky\" Phillipe", coords={x=26.9,y=73.6} },
    { action="accept", quest=607, name="Return to MacKinley", npc="\"Shaky\" Phillipe", coords={x=26.9,y=73.6} },
    { action="turnin", quest=607, name="Return to MacKinley", npc="\"Sea Wolf\" MacKinley", coords={x=27.8,y=77.1} },
    { action="accept", quest=609, name="Voodoo Dues", npc="\"Sea Wolf\" MacKinley", coords={x=27.8,y=77.1} },
    { action="accept", quest=60152, name="They Call Him Morgan the Storm", npc="\"Sea Wolf\" MacKinley", coords={x=27.8,y=77.1}, note="TurtleWoW specific." },
    { action="info", name="Bank", note="Deposit to Bank: Gorilla Fang, Stranglethorn Pages, extra Cloth", coords={x=26.7,y=76.4} },
    { action="kill", quest=604, name="The Bloodsail Buccaneers", mob="Bloodsail Swashbuckler", coords={x=29.8,y=81.3} },
    { action="turnin", quest=60152, name="They Call Him Morgan the Storm", npc="Morgan the Storm", coords={x=32.4,y=82.1}, note="TurtleWoW specific." },
    { action="accept", quest=60153, name="The Iron Patch", npc="Morgan the Storm", coords={x=32.4,y=82.1}, note="TurtleWoW specific." },
    { action="collect", quest=604, name="The Bloodsail Buccaneers", item="Bloodsail Orders", coords={x=27.7,y=83.1}, note="Click Bloodsail Orders to pick them up. In the small boat." },
    { action="collect", quest=604, name="The Bloodsail Buccaneers", item="Bloodsail Charts", coords={x=27.2,y=82.7}, note="Click Bloodsail Charts to pick them up. On the box." },
    { action="collect", quest=587, name="Up to Snuff", item="Snuff", coords={x=27,y=82}, note="Kill Bloodsail pirates to pick up Snuff." },
    { action="collect", quest=576, name="Keep An Eye Out", item="Dizzy's Eye", coords={x=33.5,y=73.3}, note="Kill Bloodsail pirates to pick up Dizzy's Eye. Very low drop chance." },
    { action="collect", quest=600, name="Venture Company Mining", item="Singing Blue Crystal", coords={x=41.1,y=43.7}, note="Kill Venture Co. Goblins to pick up Singing Blue Crystals." },
    { action="collect", quest=209, name="Skullsplitter Tusks", item="Skullsplitter Tusk", coords={x=45.9,y=42.3}, note="Kill Skullsplitter Trolls to pick up Skullsplitter Tusks." },
    { action="info", name="Booty Bay", note="Use Hearthstone to return to Booty Bay.", coords={x=45.9,y=42.3} },
    { action="turnin", quest=600, name="Venture Company Mining", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="turnin", quest=587, name="Up to Snuff", npc="Deeg", coords={x=26.9,y=77.3}},
    { action="turnin", quest=209, name="Skullsplitter Tusks", npc="Kebok", coords={x=27.0,y=77.1} },
    { action="turnin", quest=604, name="The Bloodsail Buccaneers", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0}, note="He is outside on the second floor." },
    { action="accept", quest=608, name="The Bloodsail Buccaneers", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0} },
    { action="info", name="Bank", note="Withdraw from Bank: Green Hills of Stranglethorn pages: 1, 4, 6, 8, 10, 11, 14, 16, 18, 20, 21, 24, 25, 26, 27.", coords={x=26.7,y=76.4} },
    { action="info", name="Missing Pages", note="Buy missing pages from Auctioneer O'reely next to you.", coords={x=26.6,y=76.4} },
    { action="turnin", quest=576, name="Keep An Eye Out", npc="Dizzy One-Eye",coords={x=28.6,y=75.9} },
    { action="collect", quest=617, name="Akiris by the Bundle", item="Akiris Reed", coords={x=26.0,y=62.1}, note="Kill Naga Explorers to pick up Akiris Reed." },
    { action="collect", quest=197, name="Raptor Mastery", item="Talon of Tethis", coords={x=28.6,y=44.9}, note="Kill Tethis for Talon of Tethis." },
    { action="info", name="Grind", note="Grind nearby Jungle Stalkers until Level 42.", coords={x=28.6,y=44.9} },
    { action="turnin", quest=197, name="Raptor Mastery", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="accept", quest=208, name="Big Game Hunter", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
  
    { action="accept", quest=338, name="The Green Hills of Stranglethorn", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="accept", quest=339, name="Chapter I", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="turnin", quest=339, name="Chapter I", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="accept", quest=340, name="Chapter II", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="turnin", quest=340, name="Chapter II", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="accept", quest=341, name="Chapter III", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="turnin", quest=341, name="Chapter III", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="accept", quest=342, name="Chapter IV", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="turnin", quest=342, name="Chapter IV", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="turnin", quest=338, name="The Green Hills of Stranglethorn", npc="Barnil Stonepot", coords={x=35.7,y=10.5} },
    { action="collect", quest=208, name="Big Game Hunter", item="Head of Bangalash", coords={x=38.2,y=35.6}, note="Kill King Bangalash to pick up Head of Bangalash." },
    { action="turnin", quest=208, name="Big Game Hunter", npc="Hemet Nesingwary", coords={x=35.7,y=10.8} },
    { action="info", name="Booty Bay", note="Use Hearthstone to return to Booty Bay.", coords={x=35.7,y=10.8} },
    { action="accept", quest=1116, name="Dream Dust in the Swamp", npc="Krazek", coords={x=26.9,y=77.2} },
    { action="info", name="Bank", note="Withdraw from Bank: Fuel Regulator Blueprints.", coords={x=26.7,y=76.4} },
    { action="turnin", quest=617, name="Akiris by the Bundle", npc="Privateer Bloads", coords={x=26.8,y=76.4} },
    { action="accept", quest=623, name="Akiris by the Bundle", npc="Privateer Bloads", coords={x=26.8,y=76.4} },
    { action="collect", quest=609, name="Voodoo Dues", item="Chucky's Huge Ring", coords={x=40.0,y=58.2}, note="Kill Chucky \"Ten Thumbs\" to pick up Chucky's Huge Ring." },
    { action="collect", quest=609, name="Voodoo Dues", item="Jon-Jon's Golden Spyglass", coords={x=34.9,y=51.8}, note="Kill Jon-Jon the Crow to pick up Jon-Jon's Golden Spyglass." },
    { action="collect", quest=609, name="Voodoo Dues", item="Maury's Clubbed Foot", coords={x=35.3,y=51.3}, note="Kill Maury \"Club Foot\" Wilkins to pick up Maury's Clubbed Foot." },
    { action="collect", quest=621, name="Zanzil's Secret", item="Zanzil's Mixture", coords={x=34.8,y=51.9}, note="Kill Zanzil to pick up Zanzil's Mixtures." },
    --{ action="info", name="Abandon", note="If no groups are available, abandon: Voodoo Dues, Zanzil's Secret.", coords={x=26.8,y=76.4} },
    { action="info", quest=624, name="Cortello's Riddle", coords={x=29.2,y=88.6}, note="Find and loot Cortello's Riddle, which can spawn in three different locations. In the basement of the ship." },
    { action="kill", quest=608, name="The Bloodsail Buccaneers", mob="Captain Keelhaul", coords={x=29.3,y=88.3}, note="On the first level of the ship." },
    { action="info", quest=624, name="Cortello's Riddle", coords={x=30.6,y=90.2}, note="Find and loot Cortello's Riddle, which can spawn in three different locations. Anywhere on the center ship." },
    { action="kill", quest=608, name="The Bloodsail Buccaneers", mob="Fleet Master Firallon", coords={x=30.6,y=90.6}, note="On the first level of the ship." },
    { action="collect", quest=60153, name="The Iron Patch", item="Ironpatch's Head", coords={x=30.6,y=90.4}, note="Kill Ironpatch to pick up Ironpatch's Head. On the first level of the ship. TurtleWoW specific." },
    { action="info", quest=624, name="Cortello's Riddle", coords={x=33.6,y=88.4}, note="Find and loot Cortello's Riddle, which can spawn in three different locations. On the first level of the ship." },
    { action="info", quest=624, name="Cortello's Riddle", coords={x=33.6,y=88.4}, note="Click Cortello's Riddle to accept the Quest." },
    { action="kill", quest=608, name="The Bloodsail Buccaneers", mob="Captain Stillwater", coords={x=32.9,y=88.2}, note="On the first level of the ship." },
    --{ action="info", name="Abandon", note="If no groups are available, abandon: The Bloodsail Buccaneers.", coords={x=26.8,y=76.4} },
    { action="turnin", quest=609, name="Voodoo Dues", npc="\"Sea Wolf\" MacKinley", coords={x=27.8,y=77.1} },
    { action="turnin", quest=621, name="Zanzil's Secret", npc="Crank Fizzlebub", coords={x=27.1,y=77.2} },
    { action="turnin", quest=608, name="The Bloodsail Buccaneers", npc="Fleet Master Seahorn", coords={x=27.2,y=77.0}, note="He is outside on the second floor." },
    { action="turnin", quest=60153, name="The Iron Patch", npc="Baron Revilgaz", coords={x=27.2,y=76.9}, note="TurtleWoW specific." },
    { action="info", name="Travel to Stormwind", note="Use Teleport: Stormwind or fly to Stormwind.", coords={x=74.6,y=51.0} },
    { action="accept", quest=1477, name="Vital Supplies", npc="High Sorcerer Andromath", coords={x=48.7,y=87.6}, note="Atop Wizard's Sanctum in Mage Quarter." },
    { action="info", name="Darkshire", note="Fly to Darkshire.", coords={x=71.0,y=72.5} },
    { action="turnin", quest=1477, name="Vital Supplies", npc="Watchmaster Sorigal", coords={x=75.8,y=46.2}, note="This Quest has to be turned-in within 1 hour." },
    { action="accept", quest=1395, name="Supplies for Nethergarde", npc="Watchmaster Sorigal", coords={x=75.8,y=46.2} },
    { action="info", name="Swamp of Sorrows", note="Go to the Deadwind Pass.", coords={x=91.2,y=41.5} },
    { action="info", name="Swamp of Sorrows", note="Go to the Swamp of Sorrows.", coords={x=59.8,y=41.1} },
    { nextGuide = "Swamp of Sorrows 42-43.lua" }
  }
}