LevelingGuide_Tanaris_2 = {
  steps = {
    { action="accept", quest=2605, name="The Thirsty Goblin", npc="Marin Noggenfogger", coords={x=51.8,y=28.6} },
    { action="info", name="Bind Hearthstone", note="Bind your Hearthstone to Gadgetzan at Innkeeper Fizzgrimble.", coords={x=52.5,y=27.9} },
    { action="accept", quest=5863, name="The Dunemaul Compound", npc="Andi Lynn", coords={x=52.8,y=27.4} },
    { action="turnin", quest=2941, name="The Borrower", npc="Curgle Cranklehop", coords={x=52.4,y=26.9} },
    { action="accept", quest=2944, name="The Super Snapper FX", npc="Curgle Cranklehop", coords={x=52.4,y=26.9} },
    { action="accept", quest=3022, name="Handle With Care", npc="Curgle Cranklehop", coords={x=52.4,y=26.9} },
    { action="info", quest=2741, name="The Super Egg-O-Matic", npc="Egg-O-Matic", coords={x=52.4,y=27.0}, note="You need to have a Hippogryph Egg in your inventory. Click Egg-O-Matic to turn-in this Quest." },
    --{ action="turnin", quest=2749, name="An Ordinary Egg", npc="Curgle Cranklehop", coords={x=52.4,y=26.9} },
    { action="accept", quest=3362, name="Thistleshrub Valley", npc="Tran'rek", coords={x=51.6,y=26.8} },
    { action="accept", quest=82, name="Noxious Lair Investigation", npc="Senior Surveyor Fizzledowser", coords={x=50.2,y=27.5} },
    { action="collect", quest=1452, name="Rhapsody's Kalimdor Kocktail", item="Roc Gizzard", coords={x=49.2,y=35.8}, note="Kill Rocs to pick ups Roc Gizzards." },
    { action="turnin", quest=3445, name="The Sunken Temple", npc="Marvon Rivetseeker", coords={x=52.7,y=45.9} },
    { action="accept", quest=3444, name="The Stone Circle", npc="Marvon Rivetseeker", coords={x=52.7,y=45.9} },
    { action="accept", quest=3161, name="Gahz'ridian", npc="Marvon Rivetseeker", coords={x=52.7,y=45.9} },
    { action="collect", quest=40592, name="The Gusting Vortex", item="Harmonized Sand", coords={x=43.1,y=46.5}, note="Kill Gusting Vortex to pick up Harmonized Sand. TurtleWoW specific." },
    { action="collect", quest=82, name="Noxious Lair Investigation", item="Centipaar Insect Parts", coords={x=36.0,y=45.0}, note="Kill Centipaar Wasps and Bugs to pick up Insect Parts." },
    { action="kill", quest=5863, name="The Dunemaul Compound", mob={"Gor'marok the Ravager","Dunemaul Brute","Dunemaul Enforcer"}, coords={x=41.4,y=57.8}, note="Gor'marok the Ravager is in the cave." },
    { action="collect", quest=40589, name="Chasing Sand", item="Turbo-Scan Filtronomitor", coords={x=49.5,y=59.4}, note="Click Turbo-Scan Filtronomitor to pick it up. TurtleWoW specific." },
    { action="info", name="Equip", note="Equip Gahz'ridian Detector.", coords={x=41.4,y=72.4} },
    { action="collect", quest=3161, name="Gahz'ridian", item="Gahz'ridian Ornament", coords={x=41.4,y=72.4}, note="Click Gahz'ridian Ornaments on the ground to pick them up." },
    { action="info", name="Equip", note="Equip your normal helmet.", coords={x=41.4,y=72.4} },
    { action="kill", quest=3362, name="Thistleshrub Valley", mob={"Gnarled Thistleshrub","Thistleshrub Rootshaper"}, coords={x=29.7,y=66.3} },
    { action="collect", quest=2605, name="The Thirsty Goblin", item="Laden Dew Gland", coords={x=29.9,y=64.3}, note="Kill Thistleshrub Dew Collectors to pick up a Laden Dew Gland." },
    --{ action="accept", quest=1560, name="Tooga", npc="Tooga", coords={x=28.0,y=68.0}, note="If Tooga is not here, skip this step." },
    --{ action="info", name="Escort", note="Escort Tooga northeast to Steamwheedle Port.", coords={x=28.0,y=68.0} },
    { action="turnin", quest=3161, name="Gahz'ridian", npc="Marvon Rivetseeker", coords={x=52.7,y=45.9}, note="At Broken Pillar." },
    --{ action="turnin", quest=1560, name="Tooga's Quest", npc="Torta", coords={x=66.5,y=26.0}, note="At Steamwheedle Port." },
    { action="turnin", quest=40592, name="The Gusting Vortex", npc="Ginlo Taxxo", coords={x=66.7,y=24.0}, note="TurtleWoW specific." },
    { action="turnin", quest=40589, name="Chasing Sand", npc="Baggle Hackrust", coords={x=66.8,y=24.1}, note="TurtleWoW specific." },
    { action="turnin", quest=3520, name="Screecher Spirits", npc="Yeh'kinya", coords={x=67.0,y=22.4} },
    --{ action="accept", quest=3527, name="The Prophecy of Mosh'aru", npc="Yeh'kinya", coords={x=67.0,y=22.4} },
    { action="turnin", quest=2605, name="The Thirsty Goblin", npc="Marin Noggenfogger", coords={x=51.8,y=28.6}, note="On the south side." },
    { action="accept", quest=2606, name="In Good Taste", npc="Marin Noggenfogger", coords={x=51.8,y=28.6} },
    { action="turnin", quest=5863, name="The Dunemaul Compound", npc="Andi Lynn", coords={x=52.8,y=27.4}, note="In the northeast corner." },
    { action="turnin", quest=3362, name="Thistleshrub Valley", npc="Tran'rek", coords={x=51.6,y=26.8}, note="On the north side." },
    { action="accept", quest=4504, name="Super Sticky", npc="Tran'rek", coords={x=51.6,y=26.8} },
    { action="turnin", quest=2606, name="In Good Taste", npc="Sprinkle", coords={x=51.1,y=26.9} },
    { action="accept", quest=2641, name="Sprinkle's Secret Ingredient", npc="Sprinkle", coords={x=51.1,y=26.9} },
    { action="turnin", quest=82, name="Noxious Lair Investigation", npc="Alchemist Pestlezugg", coords={x=50.9,y=27.0} },
    { action="accept", quest=10, name="The Scrimshank Redemption", npc="Senior Surveyor Fizzledowser", coords={x=50.2,y=27.5} },
    { action="info", quest=10, name="The Scrimshank Redemption", note="Go down, enter the cave and always take the left path.", coords={x=54.7,y=70.6} },
    { action="collect", quest=10, name="The Scrimshank Redemption", item="Scrimshank's Surveying Gear", 
    coords={x=56.0,y=71.2}, note="Always keep left in the cave. Click Scrimshank's Surveying Gear to pick it up." },
    { action="info", name="Hearthstone", note="Use Hearthstone to return to Gadgetzan.", coords={x=56.0,y=71.2} },
    { action="turnin", quest=10, name="The Scrimshank Redemption", npc="Senior Surveyor Fizzledowser", coords={x=50.2,y=27.5} },
    { action="accept", quest=110, name="Insect Part Analysis", npc="Senior Surveyor Fizzledowser", coords={x=50.2,y=27.5} },
    { action="turnin", quest=110, name="Insect Part Analysis", npc="Alchemist Pestlezugg", coords={x=50.9,y=27.0} },
    { action="accept", quest=113, name="Insect Part Analysis", npc="Alchemist Pestlezugg", coords={x=50.9,y=27.0} },
    { action="turnin", quest=113, name="Insect Part Analysis", npc="Senior Surveyor Fizzledowser", coords={x=50.2,y=27.5} },
    { action="accept", quest=162, name="Rise of the Silithid", npc="Senior Surveyor Fizzledowser", coords={x=50.2,y=27.5} },
    -- Zul'Farrak dungeon quests (optional)
    --{ action="accept", quest=2865, name="Scarab Shells", npc="Tran'rek", coords={x=51.6,y=26.8}, note="Dungeon quest for Zul'Farrak." },
    --{ action="accept", quest=2768, name="Divino-matic Rod", npc="Chief Engineer Bilgewhizzle", coords={x=52.5,y=28.5}, note="Dungeon quest for Zul'Farrak." },
    --{ action="accept", quest=3042, name="Troll Temper", npc="Trenton Lighthammer", coords={x=51.4,y=28.7}, note="Dungeon quest for Zul'Farrak." },
    { action="info", name="Feralas", note="Fly to Thalanaar.", coords={x=51.0,y=29.3} },
    { action="accept", quest=4281, name="Thalanaar Delivery", note="Use Undelivered Parcel in your inventory to accept this Quest.", coords={x=51.0,y=29.3} },
    { action="turnin", quest=4281, name="Thalanaar Delivery", npc="Falfindel Waywarder", coords={x=89.6,y=46.6} },
    { action="info", name="Feralas", note="Fly to Feathermoon.", coords={x=89.5,y=45.9} },
    { nextGuide = "Feralas 52.lua" }
  }
}