LevelingGuide_Thousand_Needles = {
  steps = {
    { action="accept", quest=1110, name="Rocket Car Parts", npc="Kravel Koalbeard", coords={x=77.8,y=77.3} },
    { action="accept", quest=1104, name="Salt Flat Venom", npc="Fizzle Brassbolts", coords={x=78.1,y=77.1} },
    { action="turnin", quest=1179, name="The Brassbolts Brothers", npc="Wizzle Brassbolts", coords={x=78.1,y=77.1} },
    { action="accept", quest=1105, name="Hardened Shells", npc="Wizzle Brassbolts", coords={x=78.1,y=77.1} },
    { action="turnin", quest=1949, name="Hidden Secrets", npc="Magus Tirth", coords={x=78.3,y=76.1} },
    { action="accept", quest=1950, name="Get the Scoop", npc="Magus Tirth", coords={x=78.3,y=76.1} },
    { action="info", name="Plucky Johnson", note="Go to Plucky Johnson and type /beckon to speak with him and get the password.", coords={x=79.6,y=75.6} },
    { action="turnin", quest=1950, name="Get the Scoop", npc="Magus Tirth", coords={x=78.3,y=76.1} },
    { action="accept", quest=1176, name="Load Lightening", npc="Pozzik", coords={x=80.2,y=75.9} },
    { action="accept", quest=1175, name="A Bump in the Road", npc="Trackmaster Zherin", coords={x=81.6,y=77.9} },
    { action="info", name="Grind around raceway", note="Grind all around the raceway.", coords={x=79.6,y=75.6} },
    { action="collect", quest=1176, name="Load Lightening", item="Hollow Vulture Bone", coords={x=88.0,y=65.3}, note="Kill Salt Flat Vultures to collect Hollow Vulture Bones." },
    { action="collect", quest=1105, name="Hardened Shells", item="Hardened Tortoise Shell", coords={x=77.6,y=53.9}, note="Kill Sparkleshell Tortoises to collect Hardened Tortoise Shells." },
    { action="kill", quest=1175, name="A Bump in the Road", mob={"Saltstone Basilisk","Saltstone Crystalhide","Saltstone Gazer"}, coords={x=76.9,y=60.9} },
    { action="collect", quest=1104, name="Salt Flat Venom", item="Salty Scorpid Venom", coords={x=82.7,y=79.7}, note="Kill Scorpions to collect Salty Scorpid Venom." },
    { action="collect", quest=1110, name="Rocket Car Parts", item="Rocket Car Parts", coords={x=86.2,y=74.5}, note="Pick up Rocket Car Parts from the ground." },
    { action="collect", quest=7321, name="Soothing Turtle Bisque", item="Turtle Meat", coords={x=76.2,y=58.6}, note="Kill Tortoises to collect Turtle Meat." },
    { action="turnin", quest=1110, name="Rocket Car Parts", npc="Kravel Koalbeard", coords={x=77.8,y=77.3} },
    { action="accept", quest=1111, name="Wharfmaster Dizzywig", npc="Kravel Koalbeard", coords={x=77.8,y=77.3} },
    { action="accept", quest=5762, name="Hemet Nesingwary", npc="Kravel Koalbeard", coords={x=77.8,y=77.3} },
    { action="turnin", quest=1105, name="Hardened Shells", npc="Wizzle Brassbolts", coords={x=78.1,y=77.1} },
    { action="turnin", quest=1104, name="Salt Flat Venom", npc="Fizzle Brassbolts", coords={x=78.1,y=77.1} },
    { action="accept", quest=1106, name="Martek the Exiled", npc="Fizzle Brassbolts", coords={x=78.1,y=77.1} },
    { action="turnin", quest=1176, name="Load Lightening", npc="Pozzik", coords={x=80.2,y=75.9} },
    { action="accept", quest=1178, name="Goblin Sponsorship", npc="Pozzik", coords={x=80.2,y=75.9} },
    { action="turnin", quest=1175, name="A Bump in the Road", npc="Trackmaster Zherin", coords={x=81.6,y=77.9} },
    { action="info", name="Grind", note="Grind until Level 31 and 17 bars.", coords={x=82.7,y=79.7} }, 
    { action="info", name="Tanaris", note="Go to Tanaris.", coords={x=75.5,y=97.4} },
    { action="info", name="Gadgetzan", note="Go to Gadgetzan.", coords={x=51.3,y=26.8} },
    { action="info", name="Get Flight Path", note="Get the Gadgetzan Flight Path.", coords={x=51.0,y=29.3} },
    { action="info", name="Theramore", note="Fly to Theramore.", coords={x=67.5,y=51.2} },
    { action="turnin", quest=1252, name="The Black Shield", npc="Captain Garran Vimes", coords={x=68.2,y=48.6}, note="He is up in the castle." },
    { action="accept", quest=1319, name="The Black Shield", npc="Captain Garran Vimes", coords={x=68.2,y=48.6} },
    { action="turnin", quest=1252, name="Lieutenant Paval Reethe", npc="Captain Garran Vimes", coords={x=68.2,y=48.6} },
    { action="accept", quest=1259, name="Lieutenant Paval Reethe", npc="Captain Garran Vimes", coords={x=68.2,y=48.6} },
    { action="turnin", quest=1259, name="Lieutenant Paval Reethe", npc="Adjutant Tesoran", coords={x=68.0,y=48.1} },
    { action="accept", quest=1285, name="Daelin's Men", npc="Adjutant Tesoran", coords={x=68.0,y=48.1} },
    { action="turnin", quest=1285, name="Daelin's Men", npc="Captain Garran Vimes", coords={x=68.2,y=48.6} },
    { action="turnin", quest=1248, name="Suspicious Hoofprints", npc="Captain Garran Vimes", coords={x=68.2,y=48.6} },
    { action="turnin", quest=1135, name="Highperch Venom", npc="Fiora Longears", coords={x=66.5,y=45.1}, note="She is inside the inn." },
    { action="turnin", quest=1319, name="The Black Shield", npc="Caz Twosprocket", coords={x=64.7,y=50.4} },
    { action="accept", quest=1320, name="The Black Shield", npc="Caz Twosprocket", coords={x=64.7,y=50.4} },
    { action="turnin", quest=1320, name="The Black Shield", npc="Captain Garran Vimes", coords={x=68.2,y=48.6}, note="He is up in the castle." },
    { action="info", name="The Barrens", note="Run northwest out of Theramore Isle along the north shoreline to The Barrens.", coords={x=53.3,y=10.8} },
    { action="info", name="Ratchet", note="Go to Ratchet.", coords={x=62.7,y=38.2} },
    { action="info", name="Get Flight Path", note="Get the Ratchet Flight Path.", coords={x=63.1,y=37.2} },
    { action="turnin", quest=1178, name="Goblin Sponsorship", npc="Gazlowe", coords={x=62.7,y=36.2} },
    { action="accept", quest=1180, name="Goblin Sponsorship", npc="Gazlowe", coords={x=62.7,y=36.2} },
    { action="turnin", quest=1111, name="Wharfmaster Dizzywig", npc="Wharfmaster Dizzywig", coords={x=63.3,y=38.5} },
    { action="accept", quest=1112, name="Parts for Kravel", npc="Wharfmaster Dizzywig", coords={x=63.3,y=38.5} },
    { action="info", name="Boat to Booty Bay", note="Take Boat to Booty Bay.", coords={x=63.7,y=38.6} },
    { nextGuide = "Stranglethorn 32.lua" },
  }
}
