LevelingGuide_WesternPlaguelands = {
  steps = {
    { action="turnin", quest=5091, name="A Call to Arms: The Plaguelands!", npc="Commander Ashlam Valorfist", coords={x=42.7,y=84.1} },
    { action="accept", quest=5092, name="Clear the Way", npc="Commander Ashlam Valorfist", coords={x=42.7,y=84.1} },
    { action="turnin", quest=5401, name="Argent Dawn Commission", npc="Argent Officer Pureheart", coords={x=43.0,y=83.6}, note="You can turn-in this Quest, despite being in your Quest Log." },
    { action="info", name="Equip", note="Equip the Argent Dawn Commission Trinket to gain Scourgestones.", coords={x=43.0,y=83.6} },
    { action="kill", quest=5092, name="Clear the Way", mob={"Skeletal Flayer","Slavering Ghoul"}, coords={x=48.9,y=80.6} },
    { action="turnin", quest=5092, name="Clear the Way", npc="Commander Ashlam Valorfist", coords={x=42.7,y=84.1} },
    { action="accept", quest=5215, name="The Scourge Cauldrons", npc="Commander Ashlam Valorfist", coords={x=42.7,y=84.1} },
    { action="turnin", quest=5215, name="The Scourge Cauldrons", npc="High Priestess MacDonnell", coords={x=42.9,y=84.5} },
    { action="accept", quest=5216, name="Target: Felstone Field", npc="High Priestess MacDonnell", coords={x=42.9,y=84.5} },
    { action="accept", quest=5021, name="Better Late Than Never", npc="Janice Felstone", coords={x=38.4,y=54.1}, note="She is upstairs." },
    { action="turnin", quest=5021, name="Better Late Than Never", npc="Janice Felstone", coords={x=38.7,y=55.3}, note="Click Janice's Parcel to turn-in this Quest." },
    { action="accept", quest=5022, name="Better Late Than Never", npc="Janice Felstone", coords={x=38.7,y=55.3}, note="Click Janice's Parcel to accept this Quest." },
    { action="collect", quest=5216, name="Target: Felstone Field", item="Felstone Field Cauldron Key", coords={x=37.1,y=57.2}, note="Kill Cauldron Lord Bilemaw to pick up Felstone Field Cauldron Key." },
    { action="turnin", quest=5216, name="Target: Felstone Field", npc="Scourge Cauldron", coords={x=37.2,y=56.9}, note="Click Scourge Cauldron to turn-in this Quest." },
    { action="accept", quest=5217, name="Return to Chillwind Camp", npc="Scourge Cauldron", coords={x=37.2,y=56.9} },
    { action="turnin", quest=5217, name="Return to Chillwind Camp", npc="High Priestess MacDonnell", coords={x=42.9,y=84.5} },
    { action="info", note="Turn-in Minion's Scourgestones as often as possible at Argent Officer Pureheart", coords={x=43.0,y=83.6} },
    { action="info", name="Ironforge", note="Use Teleport: Ironforge or fly to Ironforge.", coords={x=42.9,y=85.1} },
    { action="turnin", quest=3461, name="Return to Tymor", npc="Tymor", coords={x=31.0,y=4.8} },
    { action="turnin", quest=4512, name="A Little Slime Goes a Long Way", npc="Laris Geardawdle", coords={x=75.8,y=23.4} },
    { action="accept", quest=4513, name="A Little Slime Goes a Long Way", npc="Laris Geardawdle", coords={x=75.8,y=23.4}, note="Wait for RPG, then accept this Quest." },
    { action="info", name="Stormwind", note="Use Teleport: Stormwind or fly to Stormwind.", coords={x=55.5,y=47.8} },
    { action="turnin", quest=5022, name="Better Late Than Never", npc="Royal Factor Bathrilor", coords={x=57.2,y=48.1}, note="He is upstairs." },
    { action="accept", quest=5048, name="Good Natured Emma", npc="Royal Factor Bathrilor", coords={x=57.2,y=48.1} },
    { action="turnin", quest=5048, name="Good Natured Emma", npc="Ol' Emma", coords={x=60.2,y=57.0}, note="She is upstairs." },
    { action="accept", quest=5050, name="Good Luck Charm", npc="Ol' Emma", coords={x=60.2,y=57.0} },
    { action="turnin", quest=1469, name="Rhapsody's Tale", npc="Brohann Caskbelly", coords={x=69.5,y=40.4} },
    { action="info", name="Nethergarde Keep", note="Fly to Nethergarde Keep in Blasted Lands.", coords={x=71.0,y=72.5} },
    --{ action="turnin", quest=2991, name="Nekrum's Medallion", npc="Thadius Grimshade", coords={x=66.5,y=21.0} },
    --{ action="accept", quest=2992, name="The Divination", npc="Thadius Grimshade", coords={x=66.5,y=21.0} },
    --{ action="turnin", quest=2992, name="The Divination", npc="Thadius Grimshade", coords={x=66.5,y=21.0} },
    { action="accept", quest=2783, name="Petty Squabbles", npc="Ambassador Ardalan", coords={x=67.6,y=19.3} },
    { action="info", name="Swamp of Sorrows", note="Go to Swamp of Sorrows.", coords={x=52.0,y=4.7} },
    { action="turnin", quest=2783, name="Petty Squabbles", npc="Fallen Hero of the Horde", coords={x=34.3,y=66.0} },
    { action="accept", quest=2801, name="A Tale of Sorrow", npc="Fallen Hero of the Horde", coords={x=34.3,y=66.0} },
    { action="turnin", quest=2801, name="A Tale of Sorrow", npc="Fallen Hero of the Horde", coords={x=34.3,y=66.0}, note="Talk to Fallen Hero of the Horde, click through the dialogue, then turn-in the Quest." },
    { action="info", name="Blasted Lands", note="Go to Blasted Lands.", coords={x=33.1,y=68.1} },
    { action="info", name="Lakeshire", note="Fly to Lakeshire.", coords={x=65.5,y=24.3} },
    { action="info", name="Burning Steppes", note="Go to Burning Steppes.", coords={x=46.4,y=6.7} },
    { nextGuide = "Burning Steppes 54.lua" }
  }
}