LevelingGuide_Wetlands_2 = {
  steps = {
    { action="turnin", quest=270, name="The Doomed Fleet", npc="Glorin Steelbrow", coords={x=10.6,y=60.6} },
    { action="accept", quest=321, name="Lightforge Iron", npc="Glorin Steelbrow", coords={x=10.58,y=60.59} },
    { action="turnin", quest=1248, name="The Missing Diplomat", npc="Mikhail", coords={x=10.6,y=60.7} },
    { action="accept", quest=1249, name="The Missing Diplomat", npc="Mikhail", coords={x=10.6,y=60.7} },
    { action="info", name="The Missing Diplomat",  note="Kill Tapoke \"Slim\" Jahn outside.", npc="Tapoke \"Slim\" Jahn", coords={x=10.5,y=60.3} },
    { action="turnin", quest=1249, name="The Missing Diplomat", npc="Mikhail", coords={x=10.6,y=60.7} },
    { action="accept", quest=1250, name="The Missing Diplomat", npc="Tapoke \"Slim\" Jahn", coords={x=10.5,y=60.2} },
    { action="turnin", quest=1250, name="The Missing Diplomat", npc="Mikhail", coords={x=10.6,y=60.7} },
    { action="accept", quest=1264, name="The Missing Diplomat", npc="Mikhail", coords={x=10.6,y=60.7} },
    { action="info", name="Skill First Aid", note="Upstairs in the inn at Fremal Doohickey, level First Aid to 150.", coords={x=10.8,y=61.4} },
    { action="turnin", quest=321, name="Lightforge Iron", npc="Waterlogged Chest", coords={x=12.1,y=64.2} },
    { action="accept", quest=324, name="The Lost Ingots", npc="Waterlogged Chest", coords={x=12.1,y=64.2} },
    { action="collect", quest=324, name="The Lost Ingots", item="Lightforge Ingot", coords={x=12.1,y=64.2}, note="Kill Bluegill Raiders to pick up Lightforge Ingots." },
    { action="turnin", quest=324, name="The Lost Ingots", npc="Glorin Steelbrow", coords={x=10.6,y=60.6} },
    { action="accept", quest=2097, name="Fall of Dun Modr", npc="Harlo Barnaby", coords={x=10.8,y=55.9}, note="My Quest addition." },
    { action="turnin", quest=2097, name="Fall of Dun Modr", npc="Longbraid the Grim", coords={x=49.9,y=18.3}, note="My Quest addition." },
    { action="accept", quest=631, name="The Thandol Span", npc="Rhag Garmason", coords={x=49.9,y=18.2} },
    { action="info", name="Go to Arathi", note="Run north into Arathi Highlands and enter the room on the right, halfway across the bridge.", coords={x=51.5, y=7.2} },
    { action="turnin", quest=631, name="The Thandol Span", npc="Ebenezer Rustlocke's Corpse", coords={x=45.7,y=93.1} },
    { action="accept", quest=632, name="The Thandol Span", npc="Ebenezer Rustlocke's Corpse", coords={x=45.7,y=93.1} },
    { action="turnin", quest=632, name="The Thandol Span", npc="Rhag Garmason", coords={x=49.9,y=18.2} },
    { action="accept", quest=633, name="The Thandol Span", npc="Rhag Garmason", coords={x=49.9,y=18.2} },
    { action="info", name="Go to Arathi", note="Run north across the Thandol Span into Arathi Highlands.", coords={x=51.5, y=7.2} },
    { action="kill", quest=633, name="The Thandol Span", mob="Cache of Explosives", note="Destroy the Cache of Explosives", coords={x=48.8,y=88.0} },
    { action="info", name="Go to Wetlands", note="Run south across the Thandol Span into Wetlands.", coords={x=45.4, y=92.9} },
    { action="turnin", quest=633, name="The Thandol Span", npc="Rhag Garmason", coords={x=49.9,y=18.2} },
    { action="accept", quest=634, name="Plea To The Alliance", npc="Rhag Garmason", coords={x=49.9,y=18.2} },
    { action="info", name="Go to Arathi", note="Run north across the Thandol Span into Arathi Highlands.", coords={x=51.5, y=7.2} },
    { action="info", name="Do the jump!", note="Jump the gap.", coords={x=42.9, y=91.4} },
    { action="accept", quest=647, name="MacKreel's Moonshine", npc="Foggy MacKreel", coords={x=43.2,y=92.6} },
    { action="info", name="Get Flight Path", note="Get the Arathi Flight Path.", coords={x=45.7,y=46.1} },
    { action="turnin", quest=634, name="Plea To The Alliance", npc="Captain Nials", coords={x=45.8,y=47.5} },
    { action="turnin", quest=690, name="Malin's Request", npc="Skuerto", coords={x=46.6,y=47.0} },
    { action="info", name="Buy First Aid Books", note="Purchase the following First Aid Books: Expert First Aid - Under Wraps (1g), Manual: Heavy Silk Bandage (22s), Manual: Mageweave Bandage (50s). Use them all.", coords={x=26.9,y=58.8} },
    { action="info", name="Go to Hillsbrad", note="Run through Thoradin's Wall into Hillsbrad.", coords={x=19.9, y=29.5} },
    { nextGuide = "Hillsbrad 30-31.lua" },
  }
}