-- WETLANDS 24-27: https://mmo-gs.com/blog/wow-classic-20-30-alliance-leveling-guide/?utm_source=chatgpt.com
LevelingGuide_Wetlands = {
  steps = {
    { action="accept", quest=279,  name="Claws from the Deep",       npc="Karl Boran",       coords={x=8.3,y=58.6} },
    { action="accept", quest=484, name="Young Crocolisk Skins",     npc="James Halloran",         coords={x=8.5,y=55.7} },
    { action="accept", quest=288,  name="The Third Fleet",             npc="First Mate Fitzsimmons", coords={x=10.9, y=59.6} },
    { action="accept", quest=463,  name="The Greenwarden",             npc="First Mate Fitzsimmons", coords={x=10.9, y=59.6} },
    { action="info", note="Setze Menethil Harbor als Heimatort.", coords={x=10.7,y=60.9}},
    { action="info", note="Kaufe Flagon of Mead von Innkeeper Helbrek.", coords={x=10.7,y=60.9}},
    { action="turnin", quest=942, name="The Absent Minded Prospector", npc="Archaeologist Flagongut", coords={x=10.8, y=60.4} },
    { action="accept", quest=943, name="The Absent Minded Prospector", npc="Archaeologist Flagongut", coords={x=10.8, y=60.4} },
    { action="turnin", quest=288, name="The Third Fleet", npc="First Mate Fitzsimmons", coords={x=10.9, y=59.6} },
    { action="accept", quest=289, name="The Cursed Crew", npc="First Mate Fitzsimmons", coords={x=10.9, y=59.6} },
    { action="accept", quest=470, name="Digging Through the Ooze", npc="Sida", coords={x=11.8, y=58.0} },
    { action="accept", quest=473, name="Report to Captain Stoutfist", npc="Valstag Ironjaw", coords={x=10.1, y=56.9} },
    { action="info", note="Buy a Bronze Tube and a Gyrochronatom from Neal Allen in the fortress. Enter the fortress and go left.", coords={x=10.7,y=56.7}},
    { action="turnin", quest=473, name="Report to Captain Stoutfist", npc="Captain Stoutfist", coords={x=9.9, y=57.5} },
    { action="accept", quest=464, name="War Banners", npc="Captain Stoutfist", coords={x=9.9, y=57.5} },
    { action="accept", quest=55204, name="Report From Stoutfist", npc="Captain Stoutfist", coords={x=9.9, y=57.5}, note="TurtleWoW specfic." },
    { action="accept", quest=305, name="In Search of The Excavation Team", npc="Tarrel Rockweaver", coords={x=11.5, y=52.1} },    
    { action="kill", quest=279, name="Claws from the Deep", mob="Bluegill Murloc", coords={x=15.8, y=41.0}, note="Also kill Gobler to pick up Gobbler's Head." },
    { action="collect", quest=279, name="Claws from the Deep", item="Gobbler's Head", coords={x=15.8, y=41.0} },
    { action="info", note="Go to Whelgar's Excavation Site.", coords={x=35.0, y=42.0}},
    { action="accept", quest=294, name="Ormer's Revenge", npc="Ormer Ironbraid", coords={x=38.2, y=50.9} }, 
    { action="turnin", quest=305, name="In Search of The Excavation Team", npc="Merrin Rockweaver", coords={x=38.9,y=52.3} },
    { action="accept", quest=306, name="In Search of The Excavation Team", npc="Merrin Rockweaver", coords={x=38.9,y=52.3} },
    { action="collect", quest=228, item="Flagongut’s Fossil", coords={x=38.9,y=52.3}, note="Pick up Flagongut’s Fossil." },
    { action="kill", quest=294, name="Ormer's Revenge", mob={"Mottled Raptor","Mottled Screecher"}, coords={x=23.0, y=50.0} },
    { action="info", note="You should be close to level 25 now. If not, grind until you are.", {x=23.0, y=50.0} },
    { action="turnin", quest=294, name="Ormer's Revenge", npc="Ormer Ironbraid", coords={x=38.2, y=50.9} }, 
    { action="accept", quest=295, name="Ormer's Revenge", npc="Ormer Ironbraid", coords={x=38.2, y=50.9} },
    { action="accept", quest=299, name="Uncovering the Past", npc="Prospector Whelgar", coords={x=38.8, y=52.4} },
    { action="kill", quest=295, name="Ormer's Revenge", mob={"Mottled Scytheclaw","Mottled Razormaw"}, coords={x=33.7, y=49.8} },
    { action="collect", quest=299, name="Uncovering the Past", item={"Ados Fragment","Modr Fragment","Golm Fragment","Neru Fragment"}, coords={x=33.7, y=49.8}, note="Lose Soil: Neru Fragment, Vase: Golm Fragment, Slim Vase: Modr Fragment, Tomb: Ados Fragment" },
    { action="turnin", quest=295, name="Ormer's Revenge", npc="Ormer Ironbraid", coords={x=38.2, y=50.9} },
    { action="accept", quest=296, name="Ormer's Revenge", npc="Ormer Ironbraid", coords={x=38.2, y=50.9} },
    { action="turnin", quest=299, name="Uncovering the Past", npc="Prospector Whelgar", coords={x=38.8, y=52.4} },
    { action="collect", quest=296, name="Ormer's Revenge", item="Sarltooth's Talon", coords={x=33.3, y=51.5}, note="Kill Sarltooth to collect Sarltooth's Talon." },
    { action="turnin", quest=296, name="Ormer's Revenge", npc="Ormer Ironbraid", coords={x=38.2, y=50.9} },
    { action="info", note="Make sure you have looted Stone of Relu for completion of The Absent Minded Prospector. It is dropped by Mottled Raptors, Screechers, Scytheclaws, and Razormaws.", coords={x=26.0, y=47.5}},
    { action="collect", quest=464, name="War Banners", item="Dragonmaw War Banner", coords={x=44.8, y=45.3}, note="Kill Dragonmaw Orcs to collect Dragonmaw War Banners." },
    { action="accept", quest=469, name="Daily Delivery", npc="Einar Stonegrip", coords={x=49.9, y=39.3} },
    { action="info", note="Start killing Young Wetlands Crocolisks to collect Young Crocolisk Skins.", coords={x=56.4, y=40.4} },
    { action="turnin", quest=463, name="The Greenwarden", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="accept", quest=276, name="Tramping Paws", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="kill", quest=276, name="Tramping Paws", mob={"Mosshide Gnoll","Mosshide Mongrel"}, coords={x=61.0, y=58.0} },
    { action="turnin", quest=276, name="Tramping Paws", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="accept", quest=277, name="Fire Taboo", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="collect", quest=277, name="Fire Taboo", item="Crude Flint", coords={x=43.0, y=32.0}, note="Kill Mosshide Gnolls to collect Crude Flint." },
    { action="collect", quest=470, name="Digging Through the Ooze", item="Sida's Bag", coords={x=43.8, y=25.2}, note="Kill Oozes to pick up Sida's Bag." },
    { action="turnin", quest=277, name="Fire Taboo", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="accept", quest=275, name="Blisters on The Land", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="info", note="Make sure you have completed Young Wetlands Crocolisks (Collect Young Crocolisk Skins).", coords={x=56.4, y=40.4} },
    { action="accept", quest=40682, name="Raptor Ridge", npc="Dagdag Mossbelt", coords={x=55.4, y=35.7}, note="TurtleWoW specfic." },
    { action="collect", quest=40682, name="Raptor Ridge", item="Razormaw Talon", coords={x=69.3, y=32.9}, note="Kill Razormaw Raptors to pick up Razormaw Talons." },
    { action="info", note="Teleport to Menethil Harbor.", coords={x=10.7,y=60.9}},
    { action="turnin", quest=943, name="The Absent Minded Prospector", npc="Archaeologist Flagongut", coords={x=10.8, y=60.4} },
    { action="accept", quest=55100, name="Join The League!", npc="Junder Brokk", coords={x=10.8,y=60.2}, note="TurtleWoW specfic." },
    { action="turnin", quest=279,  name="Claws from the Deep", npc="Karl Boran", coords={x=8.3,y=58.6} },
    { action="accept", quest=281, name="Reclaiming Goods", npc="Karl Boran", coords={x=8.3,y=58.6} },
    { action="turnin", quest=469, name="Daily Delivery", npc="James Halloran", coords={x=8.5, y=55.7} },
    { action="turnin", quest=484, name="Young Crocolisk Skins",  npc="James Halloran", coords={x=8.5,y=55.7} },
    { action="accept", quest=471, name="Apprentice's Duties", npc="James Halloran", coords={x=8.5,y=55.7} },
    { action="turnin", quest=464, name="War Banners", npc="Captain Stoutfist", coords={x=9.9, y=57.5} },
    { action="accept", quest=465, name="Nek'rosh's Gambit", npc="Captain Stoutfist", coords={x=9.9, y=57.5} },
    { action="accept", quest=41756, name="To Crush The Dragonmaw", npc="Captain Stoutfist", coords={x=9.9, y=57.5}, note="TurtleWoW specfic." },
    { action="turnin", quest=470, name="Digging Through the Ooze", npc="Sida", coords={x=11.8, y=58.0} },
    { action="turnin", quest=306, name="In Search of The Excavation Team", npc="Tarrel Rockweaver", coords={x=11.5,y=52.1} },
    { action="accept", quest=284, name="The Search Continues", npc="Damaged Crate", coords={x=13.5, y=41.4} },
    { action="turnin", quest=284, name="The Search Continues", npc="Sealed Barrel", coords={x=13.6, y=38.2} },
    { action="accept", quest=285, name="Search More Hovels", npc="Sealed Barrel", coords={x=13.6, y=38.2} },
    { action="turnin", quest=285, name="Search More Hovels", npc="Half-buried Barrel", coords={x=13.9, y=34.8} },
    { action="accept", quest=286, name="Return the Statuette", npc="Half-buried Barrel", coords={x=13.9, y=34.8} },
    { action="kill", quest=289, name="The Cursed Crew", mob={"Cursed Sailor","Cursed Marine"}, coords={x=13.8, y=30.2}, note="Also kill First Mate Snellig to pick up Snellig's Snuffbox in the southern boat." },
    { action="collect", quest=289, name="The Cursed Crew", item="Snellig's Snuffbox", coords={x=13.8, y=30.2}, note="Kill First Mate Snellig to pick up Snellig's Snuffbox in the southern boat." },
    { action="collect", quest=471, name="Apprentice's Duties", item="Giant Crocolisk Skin", coords={x=17.5,y=23.5}, note="Kill Giant Wetland Crocolisks to collect Giant Crocolisk Skins." },
    { action="kill", quest=275, name="Blisters on The Land", mob="Fen Creeper", coords={x=37.4, y=33.4} },  
    { action="turnin", quest=275, name="Blisters on The Land", npc="Rethiel the Greenwarden", coords={x=56.4, y=40.4} },
    { action="turnin", quest=40682, name="Raptor Ridge", npc="Dagdag Mossbelt", coords={x=55.4, y=35.7}, note="TurtleWoW specfic." },
    { action="info", note="Grind until your Hearthstone is up again.", coords={x=55.4, y=35.7} },
    { action="info", name="Go to Arathi", note="Go north to the Arathi Highlands.", coords={x=51.5, y=7.2} },
    { action="info", name="Pick up Waterlogged Letter", note="Jump down the bridge and pick up the Waterlogged Letter.", coords={x=44.3, y=92.9} },
    { action="info", name="Open Waterlogged Letter", note="Jump down the bridge and pick up the Waterlogged Letter.", coords={x=44.3, y=92.9} },
    { action="accept", quest=637, name="Sully Balloo's Letter", npc="Waterlogged Envelope", note="Open the Waterlogged Letter to start Sully Balloo's Letter." },
    { action="info", note="Teleport to Menethil Harbor.", coords={x=10.7,y=60.9}},
    { action="turnin", quest=289, name="The Cursed Crew", npc="First Mate Fitzsimmons", coords={x=10.9, y=59.6} },
    { action="accept", quest=290, name="Lifting the Curse", npc="First Mate Fitzsimmons", coords={x=10.9, y=59.6} },
    { action="turnin", quest=471, name="Apprentice's Duties", npc="James Halloran", coords={x=8.5,y=55.7} },
    { action="turnin", quest=286, name="Return the Statuette", npc="Karl Boran", coords={x=8.3,y=58.6} },
    -- TODO: Folgende Quests so einsortieren, dass sie mit der Raptor-Kill- / Sida's Bag Quest gleichzeitig erledigt werden.
    { action="turnin", quest=55204, name="Report From Stoutfist", npc="Captain Snowbeard", coords={x=27.4,y=66.5}, note="TurtleWoW specfic." },
    { action="accept", quest=55205, name="Report From Snowbeard", npc="Captain Snowbeard", coords={x=27.4,y=66.5}, note="TurtleWoW specfic." },
    { action="accept", quest=55201, name="Retaking The Roadways", npc="Captain Snowbeard", coords={x=27.4,y=66.5}, note="TurtleWoW specfic." },
    { action="accept", quest=55200, name="Preparations for Adventure!", npc="Samuel Vickers", coords={x=31.0,y=64.3}, note="TurtleWoW specfic." },
    { action="collect", quest=55201, name="Retaking The Roadways", item="Mottled Talon", coords={x=23.3,y=54.3}, note="Kill Mottled Raptors to collect Mottled Talons." },
    { action="collect", quest=55200, name="Preparations for Adventure!", item={"Sticky Ooze-Tar","Simple Wood"},coords={x=43.8,y=25.2}, note="Kill Oozes to collect Sticky Ooze-Tar." },
    { action="info", note="Buy 5x Simple Wood from Neal Allen in the fortress. Enter the fortress and go left. TurtleWoW specfic.", coords={x=10.7,y=56.7}},
    { action="turnin", quest=55205, name="Report From Snowbeard", npc="Captain Stoutfist", coords={x=9.9, y=57.5}, note="TurtleWoW specfic." },
    { action="accept", quest=55206, name="Hunting Dragonmaw", npc="Captain Snowbeard", coords={x=27.4,y=66.5}, note="TurtleWoW specfic." },
    { action="turnin", quest=55201, name="Retaking The Roadways", npc="Captain Snowbeard", coords={x=27.4,y=66.5}, note="TurtleWoW specfic." },
    { action="turnin", quest=55200, name="Preparations for Adventure!", npc="Samuel Vickers", coords={x=31.0,y=64.3}, note="TurtleWoW specfic." },
    { action="info", name="Fly to Ironforge", note="Fly to Ironforge.", coords={x=9.5, y=59.7}},
    --[[
    2) Buy Bronze Tube if you haven’t yet.
    3) If you have the Book: The Powers Below, turn in “The Powers Below”.
    4) Turn in  “An Old Colleague”, buy 4 Minor Mana Potions and 2 Elixirs of Minor Fortitude and accept/turn in Ineptitude + Chemicals = Fun, SKIP the next part.
    --]]
    { action="turnin", quest=637, name="Sully Balloo's Letter", npc="Sara Balloo", coords={x=63.4,y=67.2} },
    { action="accept", quest=683, name="Sara Balloo's Plea", npc="Sara Balloo", coords={x=63.4,y=67.2} },
    { action="turnin", quest=683, name="Sara Balloo's Plea", npc="King Magni Bronzebeard", coords={x=39.0,y=56.1} },
    { action="accept", quest=686, name="A King's Tribute", npc="King Magni Bronzebeard", coords={x=39.0,y=56.1} },
    { action="turnin", quest=686, name="A King's Tribute", npc="Grand Mason Marblesten", coords={x=39.0,y=87.9} },
    { action="accept", quest=689, name="A King's Tribute", npc="Grand Mason Marblesten", coords={x=39.0,y=87.9} },
    { action="info", name="Fly to Stormwind", note="Fly to Stormwind.", coords={x=55.2, y=47.7}},
    { action="accept", quest=335, name="A Noble Brew", npc="Zardeth of the Black Claw", coords={x=40.1,y=85.0} },
    --{ action="info", name="Fly to Lakeshire", note="Fly to Lakeshire.", coords={x=73.4, y=70.4}},
    { action="accept", quest=41798, name="My Darling Wife", npc="Ronald Gillian", coords={x=51.6,y=57.8}, note="TurtleWoW specfic." },
    { action="accept", quest=41799, name="A Hydromancer's Curiosity", npc="Marine Hornby", coords={x=28.7,y=11.5}, note="TurtleWoW specfic." },
    { action="info", name="Go to Steelwing.", note="Go to Steelwing and fly to Balor.", coords={x=21.5, y=41.5}, note="TurtleWoW specfic." },
      -- Automatischer Übergang zum nächsten Guide
    { nextGuide = "Duskwood 28-30.lua" },
  }
}